//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("JobZoomModel", "FK__DecisionT__NODEI__145C0A3F", "DecisionTreeNode", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JobZoom.Core.DecisionTreeNode), "DecisionTreeNodeDistribution", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(JobZoom.Core.DecisionTreeNodeDistribution), true)]
[assembly: EdmRelationshipAttribute("JobZoomModel", "FK_TagAttribute_TagAttribute", "TagAttribute", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(JobZoom.Core.TagAttribute), "TagAttribute1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JobZoom.Core.TagAttribute), true)]

#endregion

namespace JobZoom.Core
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class JobZoomEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new JobZoomEntities object using the connection string found in the 'JobZoomEntities' section of the application configuration file.
        /// </summary>
        public JobZoomEntities() : base("name=JobZoomEntities", "JobZoomEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new JobZoomEntities object.
        /// </summary>
        public JobZoomEntities(string connectionString) : base(connectionString, "JobZoomEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new JobZoomEntities object.
        /// </summary>
        public JobZoomEntities(EntityConnection connection) : base(connection, "JobZoomEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DecisionTreeNode> DecisionTreeNodes
        {
            get
            {
                if ((_DecisionTreeNodes == null))
                {
                    _DecisionTreeNodes = base.CreateObjectSet<DecisionTreeNode>("DecisionTreeNodes");
                }
                return _DecisionTreeNodes;
            }
        }
        private ObjectSet<DecisionTreeNode> _DecisionTreeNodes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DecisionTreeNodeDistribution> DecisionTreeNodeDistributions
        {
            get
            {
                if ((_DecisionTreeNodeDistributions == null))
                {
                    _DecisionTreeNodeDistributions = base.CreateObjectSet<DecisionTreeNodeDistribution>("DecisionTreeNodeDistributions");
                }
                return _DecisionTreeNodeDistributions;
            }
        }
        private ObjectSet<DecisionTreeNodeDistribution> _DecisionTreeNodeDistributions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SimilarityTerm> SimilarityTerms
        {
            get
            {
                if ((_SimilarityTerms == null))
                {
                    _SimilarityTerms = base.CreateObjectSet<SimilarityTerm>("SimilarityTerms");
                }
                return _SimilarityTerms;
            }
        }
        private ObjectSet<SimilarityTerm> _SimilarityTerms;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TagAttribute> TagAttributes
        {
            get
            {
                if ((_TagAttributes == null))
                {
                    _TagAttributes = base.CreateObjectSet<TagAttribute>("TagAttributes");
                }
                return _TagAttributes;
            }
        }
        private ObjectSet<TagAttribute> _TagAttributes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DecisionTreeNodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDecisionTreeNodes(DecisionTreeNode decisionTreeNode)
        {
            base.AddObject("DecisionTreeNodes", decisionTreeNode);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DecisionTreeNodeDistributions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDecisionTreeNodeDistributions(DecisionTreeNodeDistribution decisionTreeNodeDistribution)
        {
            base.AddObject("DecisionTreeNodeDistributions", decisionTreeNodeDistribution);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SimilarityTerms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSimilarityTerms(SimilarityTerm similarityTerm)
        {
            base.AddObject("SimilarityTerms", similarityTerm);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TagAttributes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTagAttributes(TagAttribute tagAttribute)
        {
            base.AddObject("TagAttributes", tagAttribute);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JobZoomModel", Name="DecisionTreeNode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DecisionTreeNode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DecisionTreeNode object.
        /// </summary>
        /// <param name="nODEID">Initial value of the NODEID property.</param>
        public static DecisionTreeNode CreateDecisionTreeNode(global::System.String nODEID)
        {
            DecisionTreeNode decisionTreeNode = new DecisionTreeNode();
            decisionTreeNode.NODEID = nODEID;
            return decisionTreeNode;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NODEID
        {
            get
            {
                return _NODEID;
            }
            set
            {
                if (_NODEID != value)
                {
                    OnNODEIDChanging(value);
                    ReportPropertyChanging("NODEID");
                    _NODEID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("NODEID");
                    OnNODEIDChanged();
                }
            }
        }
        private global::System.String _NODEID;
        partial void OnNODEIDChanging(global::System.String value);
        partial void OnNODEIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NODE_TYPE
        {
            get
            {
                return _NODE_TYPE;
            }
            set
            {
                OnNODE_TYPEChanging(value);
                ReportPropertyChanging("NODE_TYPE");
                _NODE_TYPE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NODE_TYPE");
                OnNODE_TYPEChanged();
            }
        }
        private Nullable<global::System.Int32> _NODE_TYPE;
        partial void OnNODE_TYPEChanging(Nullable<global::System.Int32> value);
        partial void OnNODE_TYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NODE_CAPTION
        {
            get
            {
                return _NODE_CAPTION;
            }
            set
            {
                OnNODE_CAPTIONChanging(value);
                ReportPropertyChanging("NODE_CAPTION");
                _NODE_CAPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NODE_CAPTION");
                OnNODE_CAPTIONChanged();
            }
        }
        private global::System.String _NODE_CAPTION;
        partial void OnNODE_CAPTIONChanging(global::System.String value);
        partial void OnNODE_CAPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CHILDREN_CARDINALITY
        {
            get
            {
                return _CHILDREN_CARDINALITY;
            }
            set
            {
                OnCHILDREN_CARDINALITYChanging(value);
                ReportPropertyChanging("CHILDREN_CARDINALITY");
                _CHILDREN_CARDINALITY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CHILDREN_CARDINALITY");
                OnCHILDREN_CARDINALITYChanged();
            }
        }
        private Nullable<global::System.Int32> _CHILDREN_CARDINALITY;
        partial void OnCHILDREN_CARDINALITYChanging(Nullable<global::System.Int32> value);
        partial void OnCHILDREN_CARDINALITYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PARENTID
        {
            get
            {
                return _PARENTID;
            }
            set
            {
                OnPARENTIDChanging(value);
                ReportPropertyChanging("PARENTID");
                _PARENTID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PARENTID");
                OnPARENTIDChanged();
            }
        }
        private global::System.String _PARENTID;
        partial void OnPARENTIDChanging(global::System.String value);
        partial void OnPARENTIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NODE_DESCRIPTION
        {
            get
            {
                return _NODE_DESCRIPTION;
            }
            set
            {
                OnNODE_DESCRIPTIONChanging(value);
                ReportPropertyChanging("NODE_DESCRIPTION");
                _NODE_DESCRIPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NODE_DESCRIPTION");
                OnNODE_DESCRIPTIONChanged();
            }
        }
        private global::System.String _NODE_DESCRIPTION;
        partial void OnNODE_DESCRIPTIONChanging(global::System.String value);
        partial void OnNODE_DESCRIPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NODE_RULE
        {
            get
            {
                return _NODE_RULE;
            }
            set
            {
                OnNODE_RULEChanging(value);
                ReportPropertyChanging("NODE_RULE");
                _NODE_RULE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NODE_RULE");
                OnNODE_RULEChanged();
            }
        }
        private global::System.String _NODE_RULE;
        partial void OnNODE_RULEChanging(global::System.String value);
        partial void OnNODE_RULEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MARGINAL_RULE
        {
            get
            {
                return _MARGINAL_RULE;
            }
            set
            {
                OnMARGINAL_RULEChanging(value);
                ReportPropertyChanging("MARGINAL_RULE");
                _MARGINAL_RULE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MARGINAL_RULE");
                OnMARGINAL_RULEChanged();
            }
        }
        private global::System.String _MARGINAL_RULE;
        partial void OnMARGINAL_RULEChanging(global::System.String value);
        partial void OnMARGINAL_RULEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> NODE_PROBABILITY
        {
            get
            {
                return _NODE_PROBABILITY;
            }
            set
            {
                OnNODE_PROBABILITYChanging(value);
                ReportPropertyChanging("NODE_PROBABILITY");
                _NODE_PROBABILITY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NODE_PROBABILITY");
                OnNODE_PROBABILITYChanged();
            }
        }
        private Nullable<global::System.Double> _NODE_PROBABILITY;
        partial void OnNODE_PROBABILITYChanging(Nullable<global::System.Double> value);
        partial void OnNODE_PROBABILITYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> MARGINAL_PROBABILITY
        {
            get
            {
                return _MARGINAL_PROBABILITY;
            }
            set
            {
                OnMARGINAL_PROBABILITYChanging(value);
                ReportPropertyChanging("MARGINAL_PROBABILITY");
                _MARGINAL_PROBABILITY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MARGINAL_PROBABILITY");
                OnMARGINAL_PROBABILITYChanged();
            }
        }
        private Nullable<global::System.Double> _MARGINAL_PROBABILITY;
        partial void OnMARGINAL_PROBABILITYChanging(Nullable<global::System.Double> value);
        partial void OnMARGINAL_PROBABILITYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> NODE_SUPPORT
        {
            get
            {
                return _NODE_SUPPORT;
            }
            set
            {
                OnNODE_SUPPORTChanging(value);
                ReportPropertyChanging("NODE_SUPPORT");
                _NODE_SUPPORT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NODE_SUPPORT");
                OnNODE_SUPPORTChanged();
            }
        }
        private Nullable<global::System.Double> _NODE_SUPPORT;
        partial void OnNODE_SUPPORTChanging(Nullable<global::System.Double> value);
        partial void OnNODE_SUPPORTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MSOLAP_MODEL_COLUMN
        {
            get
            {
                return _MSOLAP_MODEL_COLUMN;
            }
            set
            {
                OnMSOLAP_MODEL_COLUMNChanging(value);
                ReportPropertyChanging("MSOLAP_MODEL_COLUMN");
                _MSOLAP_MODEL_COLUMN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MSOLAP_MODEL_COLUMN");
                OnMSOLAP_MODEL_COLUMNChanged();
            }
        }
        private global::System.String _MSOLAP_MODEL_COLUMN;
        partial void OnMSOLAP_MODEL_COLUMNChanging(global::System.String value);
        partial void OnMSOLAP_MODEL_COLUMNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> MSOLAP_NODE_SCORE
        {
            get
            {
                return _MSOLAP_NODE_SCORE;
            }
            set
            {
                OnMSOLAP_NODE_SCOREChanging(value);
                ReportPropertyChanging("MSOLAP_NODE_SCORE");
                _MSOLAP_NODE_SCORE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MSOLAP_NODE_SCORE");
                OnMSOLAP_NODE_SCOREChanged();
            }
        }
        private Nullable<global::System.Double> _MSOLAP_NODE_SCORE;
        partial void OnMSOLAP_NODE_SCOREChanging(Nullable<global::System.Double> value);
        partial void OnMSOLAP_NODE_SCOREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MSOLAP_NODE_SHORT_CAPTION
        {
            get
            {
                return _MSOLAP_NODE_SHORT_CAPTION;
            }
            set
            {
                OnMSOLAP_NODE_SHORT_CAPTIONChanging(value);
                ReportPropertyChanging("MSOLAP_NODE_SHORT_CAPTION");
                _MSOLAP_NODE_SHORT_CAPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MSOLAP_NODE_SHORT_CAPTION");
                OnMSOLAP_NODE_SHORT_CAPTIONChanged();
            }
        }
        private global::System.String _MSOLAP_NODE_SHORT_CAPTION;
        partial void OnMSOLAP_NODE_SHORT_CAPTIONChanging(global::System.String value);
        partial void OnMSOLAP_NODE_SHORT_CAPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ATTRIBUTE_NAME
        {
            get
            {
                return _ATTRIBUTE_NAME;
            }
            set
            {
                OnATTRIBUTE_NAMEChanging(value);
                ReportPropertyChanging("ATTRIBUTE_NAME");
                _ATTRIBUTE_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ATTRIBUTE_NAME");
                OnATTRIBUTE_NAMEChanged();
            }
        }
        private global::System.String _ATTRIBUTE_NAME;
        partial void OnATTRIBUTE_NAMEChanging(global::System.String value);
        partial void OnATTRIBUTE_NAMEChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JobZoomModel", "FK__DecisionT__NODEI__145C0A3F", "DecisionTreeNodeDistribution")]
        public DecisionTreeNodeDistribution DecisionTreeNodeDistribution
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DecisionTreeNodeDistribution>("JobZoomModel.FK__DecisionT__NODEI__145C0A3F", "DecisionTreeNodeDistribution").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DecisionTreeNodeDistribution>("JobZoomModel.FK__DecisionT__NODEI__145C0A3F", "DecisionTreeNodeDistribution").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DecisionTreeNodeDistribution> DecisionTreeNodeDistributionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DecisionTreeNodeDistribution>("JobZoomModel.FK__DecisionT__NODEI__145C0A3F", "DecisionTreeNodeDistribution");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DecisionTreeNodeDistribution>("JobZoomModel.FK__DecisionT__NODEI__145C0A3F", "DecisionTreeNodeDistribution", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JobZoomModel", Name="DecisionTreeNodeDistribution")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DecisionTreeNodeDistribution : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DecisionTreeNodeDistribution object.
        /// </summary>
        /// <param name="nODEID">Initial value of the NODEID property.</param>
        public static DecisionTreeNodeDistribution CreateDecisionTreeNodeDistribution(global::System.String nODEID)
        {
            DecisionTreeNodeDistribution decisionTreeNodeDistribution = new DecisionTreeNodeDistribution();
            decisionTreeNodeDistribution.NODEID = nODEID;
            return decisionTreeNodeDistribution;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NODEID
        {
            get
            {
                return _NODEID;
            }
            set
            {
                if (_NODEID != value)
                {
                    OnNODEIDChanging(value);
                    ReportPropertyChanging("NODEID");
                    _NODEID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("NODEID");
                    OnNODEIDChanged();
                }
            }
        }
        private global::System.String _NODEID;
        partial void OnNODEIDChanging(global::System.String value);
        partial void OnNODEIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ATTRIBUTE_NAME
        {
            get
            {
                return _ATTRIBUTE_NAME;
            }
            set
            {
                OnATTRIBUTE_NAMEChanging(value);
                ReportPropertyChanging("ATTRIBUTE_NAME");
                _ATTRIBUTE_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ATTRIBUTE_NAME");
                OnATTRIBUTE_NAMEChanged();
            }
        }
        private global::System.String _ATTRIBUTE_NAME;
        partial void OnATTRIBUTE_NAMEChanging(global::System.String value);
        partial void OnATTRIBUTE_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ATTRIBUTE_VALUE
        {
            get
            {
                return _ATTRIBUTE_VALUE;
            }
            set
            {
                OnATTRIBUTE_VALUEChanging(value);
                ReportPropertyChanging("ATTRIBUTE_VALUE");
                _ATTRIBUTE_VALUE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ATTRIBUTE_VALUE");
                OnATTRIBUTE_VALUEChanged();
            }
        }
        private global::System.String _ATTRIBUTE_VALUE;
        partial void OnATTRIBUTE_VALUEChanging(global::System.String value);
        partial void OnATTRIBUTE_VALUEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> SUPPORT
        {
            get
            {
                return _SUPPORT;
            }
            set
            {
                OnSUPPORTChanging(value);
                ReportPropertyChanging("SUPPORT");
                _SUPPORT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SUPPORT");
                OnSUPPORTChanged();
            }
        }
        private Nullable<global::System.Double> _SUPPORT;
        partial void OnSUPPORTChanging(Nullable<global::System.Double> value);
        partial void OnSUPPORTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PROBABILITY
        {
            get
            {
                return _PROBABILITY;
            }
            set
            {
                OnPROBABILITYChanging(value);
                ReportPropertyChanging("PROBABILITY");
                _PROBABILITY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PROBABILITY");
                OnPROBABILITYChanged();
            }
        }
        private Nullable<global::System.Double> _PROBABILITY;
        partial void OnPROBABILITYChanging(Nullable<global::System.Double> value);
        partial void OnPROBABILITYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> VARIANCE
        {
            get
            {
                return _VARIANCE;
            }
            set
            {
                OnVARIANCEChanging(value);
                ReportPropertyChanging("VARIANCE");
                _VARIANCE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VARIANCE");
                OnVARIANCEChanged();
            }
        }
        private Nullable<global::System.Double> _VARIANCE;
        partial void OnVARIANCEChanging(Nullable<global::System.Double> value);
        partial void OnVARIANCEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> VALUETYPE
        {
            get
            {
                return _VALUETYPE;
            }
            set
            {
                OnVALUETYPEChanging(value);
                ReportPropertyChanging("VALUETYPE");
                _VALUETYPE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VALUETYPE");
                OnVALUETYPEChanged();
            }
        }
        private Nullable<global::System.Int32> _VALUETYPE;
        partial void OnVALUETYPEChanging(Nullable<global::System.Int32> value);
        partial void OnVALUETYPEChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JobZoomModel", "FK__DecisionT__NODEI__145C0A3F", "DecisionTreeNode")]
        public DecisionTreeNode DecisionTreeNode
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DecisionTreeNode>("JobZoomModel.FK__DecisionT__NODEI__145C0A3F", "DecisionTreeNode").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DecisionTreeNode>("JobZoomModel.FK__DecisionT__NODEI__145C0A3F", "DecisionTreeNode").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DecisionTreeNode> DecisionTreeNodeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DecisionTreeNode>("JobZoomModel.FK__DecisionT__NODEI__145C0A3F", "DecisionTreeNode");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DecisionTreeNode>("JobZoomModel.FK__DecisionT__NODEI__145C0A3F", "DecisionTreeNode", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JobZoomModel", Name="SimilarityTerm")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SimilarityTerm : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SimilarityTerm object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="keyword1">Initial value of the Keyword1 property.</param>
        /// <param name="keyword2">Initial value of the Keyword2 property.</param>
        /// <param name="rate">Initial value of the Rate property.</param>
        public static SimilarityTerm CreateSimilarityTerm(global::System.String id, global::System.String keyword1, global::System.String keyword2, global::System.Double rate)
        {
            SimilarityTerm similarityTerm = new SimilarityTerm();
            similarityTerm.ID = id;
            similarityTerm.Keyword1 = keyword1;
            similarityTerm.Keyword2 = keyword2;
            similarityTerm.Rate = rate;
            return similarityTerm;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Keyword1
        {
            get
            {
                return _Keyword1;
            }
            set
            {
                OnKeyword1Changing(value);
                ReportPropertyChanging("Keyword1");
                _Keyword1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Keyword1");
                OnKeyword1Changed();
            }
        }
        private global::System.String _Keyword1;
        partial void OnKeyword1Changing(global::System.String value);
        partial void OnKeyword1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Keyword2
        {
            get
            {
                return _Keyword2;
            }
            set
            {
                OnKeyword2Changing(value);
                ReportPropertyChanging("Keyword2");
                _Keyword2 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Keyword2");
                OnKeyword2Changed();
            }
        }
        private global::System.String _Keyword2;
        partial void OnKeyword2Changing(global::System.String value);
        partial void OnKeyword2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Rate
        {
            get
            {
                return _Rate;
            }
            set
            {
                OnRateChanging(value);
                ReportPropertyChanging("Rate");
                _Rate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rate");
                OnRateChanged();
            }
        }
        private global::System.Double _Rate;
        partial void OnRateChanging(global::System.Double value);
        partial void OnRateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JobZoomModel", Name="TagAttribute")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TagAttribute : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TagAttribute object.
        /// </summary>
        /// <param name="tagId">Initial value of the TagId property.</param>
        /// <param name="tagName">Initial value of the TagName property.</param>
        public static TagAttribute CreateTagAttribute(global::System.Guid tagId, global::System.String tagName)
        {
            TagAttribute tagAttribute = new TagAttribute();
            tagAttribute.TagId = tagId;
            tagAttribute.TagName = tagName;
            return tagAttribute;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TagId
        {
            get
            {
                return _TagId;
            }
            set
            {
                if (_TagId != value)
                {
                    OnTagIdChanging(value);
                    ReportPropertyChanging("TagId");
                    _TagId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TagId");
                    OnTagIdChanged();
                }
            }
        }
        private global::System.Guid _TagId;
        partial void OnTagIdChanging(global::System.Guid value);
        partial void OnTagIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TagName
        {
            get
            {
                return _TagName;
            }
            set
            {
                OnTagNameChanging(value);
                ReportPropertyChanging("TagName");
                _TagName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TagName");
                OnTagNameChanged();
            }
        }
        private global::System.String _TagName;
        partial void OnTagNameChanging(global::System.String value);
        partial void OnTagNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                OnWeightChanging(value);
                ReportPropertyChanging("Weight");
                _Weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Weight");
                OnWeightChanged();
            }
        }
        private Nullable<global::System.Int16> _Weight;
        partial void OnWeightChanging(Nullable<global::System.Int16> value);
        partial void OnWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Level
        {
            get
            {
                return _Level;
            }
            set
            {
                OnLevelChanging(value);
                ReportPropertyChanging("Level");
                _Level = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Level");
                OnLevelChanged();
            }
        }
        private Nullable<global::System.Int16> _Level;
        partial void OnLevelChanging(Nullable<global::System.Int16> value);
        partial void OnLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Required
        {
            get
            {
                return _Required;
            }
            set
            {
                OnRequiredChanging(value);
                ReportPropertyChanging("Required");
                _Required = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Required");
                OnRequiredChanged();
            }
        }
        private Nullable<global::System.Boolean> _Required;
        partial void OnRequiredChanging(Nullable<global::System.Boolean> value);
        partial void OnRequiredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TableReference
        {
            get
            {
                return _TableReference;
            }
            set
            {
                OnTableReferenceChanging(value);
                ReportPropertyChanging("TableReference");
                _TableReference = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TableReference");
                OnTableReferenceChanged();
            }
        }
        private global::System.String _TableReference;
        partial void OnTableReferenceChanging(global::System.String value);
        partial void OnTableReferenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ObjectId
        {
            get
            {
                return _ObjectId;
            }
            set
            {
                OnObjectIdChanging(value);
                ReportPropertyChanging("ObjectId");
                _ObjectId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ObjectId");
                OnObjectIdChanged();
            }
        }
        private Nullable<global::System.Guid> _ObjectId;
        partial void OnObjectIdChanging(Nullable<global::System.Guid> value);
        partial void OnObjectIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private Nullable<global::System.Guid> _ParentId;
        partial void OnParentIdChanging(Nullable<global::System.Guid> value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ParentName
        {
            get
            {
                return _ParentName;
            }
            set
            {
                OnParentNameChanging(value);
                ReportPropertyChanging("ParentName");
                _ParentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ParentName");
                OnParentNameChanged();
            }
        }
        private global::System.String _ParentName;
        partial void OnParentNameChanging(global::System.String value);
        partial void OnParentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Attachment
        {
            get
            {
                return _Attachment;
            }
            set
            {
                OnAttachmentChanging(value);
                ReportPropertyChanging("Attachment");
                _Attachment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Attachment");
                OnAttachmentChanged();
            }
        }
        private global::System.String _Attachment;
        partial void OnAttachmentChanging(global::System.String value);
        partial void OnAttachmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JobZoomModel", "FK_TagAttribute_TagAttribute", "TagAttribute1")]
        public EntityCollection<TagAttribute> TagAttribute1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TagAttribute>("JobZoomModel.FK_TagAttribute_TagAttribute", "TagAttribute1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TagAttribute>("JobZoomModel.FK_TagAttribute_TagAttribute", "TagAttribute1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JobZoomModel", "FK_TagAttribute_TagAttribute", "TagAttribute")]
        public TagAttribute TagAttribute2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TagAttribute>("JobZoomModel.FK_TagAttribute_TagAttribute", "TagAttribute").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TagAttribute>("JobZoomModel.FK_TagAttribute_TagAttribute", "TagAttribute").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TagAttribute> TagAttribute2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TagAttribute>("JobZoomModel.FK_TagAttribute_TagAttribute", "TagAttribute");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TagAttribute>("JobZoomModel.FK_TagAttribute_TagAttribute", "TagAttribute", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
