//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobZoom.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public System.Guid CompanyId { get; set; }
        public string Name { get; set; }
        public string Industry { get; set; }
        public string CompanySize { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Phone { get; set; }
        public string MobilePhone { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public string Faceboook { get; set; }
        public string Twitter { get; set; }
        public string Linkedin { get; set; }
        public string Logo { get; set; }
        public string Email { get; set; }
    }
}
