//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobZoom.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Approval
    {
        public System.Guid JobApprovalId { get; set; }
        public System.Guid JobPostingId { get; set; }
        public System.Guid ProfileID { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> IsApplied { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    }
}
