//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobZoom.Business.Entities
{
    using System;
    using System.Collections.Generic;
    using JobZoom.Core.FlexibleAttributes;
    
    [TagContract]
    public partial class Job_Posting
    {
        public Job_Posting()
        {
            this.Job_EducationExpRequirement = new HashSet<Job_EducationExpRequirement>();
            this.Job_OtherRequirement = new HashSet<Job_OtherRequirement>();
            this.Job_WorkExpRequirement = new HashSet<Job_WorkExpRequirement>();
        }
    
        public System.Guid JobPostingId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }

        [TagMember(TaggingType = TaggingType.ColumnNameAsTag)]
        public string CompanyName { get; set; }
        public string JobTitle { get; set; }
    
        public virtual ICollection<Job_EducationExpRequirement> Job_EducationExpRequirement { get; set; }
        public virtual ICollection<Job_OtherRequirement> Job_OtherRequirement { get; set; }
        public virtual ICollection<Job_WorkExpRequirement> Job_WorkExpRequirement { get; set; }
    }
}
