//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobZoom.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile_Work
    {
        public System.Guid ProfileWorkId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string JobTitle { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> CurrentlyWork { get; set; }
        public string Description { get; set; }
    
        public virtual User User { get; set; }
    }
}
