//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="InformationConnectionsEngine.data")]
[System.Xml.Serialization.XmlRootAttribute("iceData", Namespace="InformationConnectionsEngine.data", IsNullable=false)]
public partial class Root {
    
    private RootCurrentNode currentNodeField;
    
    private Node[] neighborsField;
    
    /// <remarks/>
    public RootCurrentNode currentNode {
        get {
            return this.currentNodeField;
        }
        set {
            this.currentNodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("node", IsNullable=false)]
    public Node[] neighbors {
        get {
            return this.neighborsField;
        }
        set {
            this.neighborsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="InformationConnectionsEngine.data")]
public partial class RootCurrentNode {
    
    private Node nodeField;
    
    private Link[] linkField;
    
    /// <remarks/>
    public Node node {
        get {
            return this.nodeField;
        }
        set {
            this.nodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("link")]
    public Link[] link {
        get {
            return this.linkField;
        }
        set {
            this.linkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="InformationConnectionsEngine.data")]
public partial class Node {
    
    private Action[] actionsField;
    
    private NodeDrawingInformation drawingInformationField;
    
    private string refreshRateField;
    
    private string relativeSizeField;
    
    private string styleField;
    
    private string titleField;
    
    private string typeField;
    
    private string urlField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("action", IsNullable=false)]
    public Action[] actions {
        get {
            return this.actionsField;
        }
        set {
            this.actionsField = value;
        }
    }
    
    /// <remarks/>
    public NodeDrawingInformation drawingInformation {
        get {
            return this.drawingInformationField;
        }
        set {
            this.drawingInformationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
    public string refreshRate {
        get {
            return this.refreshRateField;
        }
        set {
            this.refreshRateField = value;
        }
    }
    
    /// <remarks/>
    public string relativeSize {
        get {
            return this.relativeSizeField;
        }
        set {
            this.relativeSizeField = value;
        }
    }
    
    /// <remarks/>
    public string style {
        get {
            return this.styleField;
        }
        set {
            this.styleField = value;
        }
    }
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="InformationConnectionsEngine.data")]
public partial class Action {
    
    private System.Xml.XmlElement[] anyField;
    
    private string idrefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string idref {
        get {
            return this.idrefField;
        }
        set {
            this.idrefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="InformationConnectionsEngine.data")]
public partial class Link {
    
    private Action[] actionsField;
    
    private LinkDrawingInformation drawingInformationField;
    
    private LinkGrammar grammarField;
    
    private float strengthField;
    
    private string styleField;
    
    private string idField;
    
    private string toField;
    
    private string fromField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("action", IsNullable=false)]
    public Action[] actions {
        get {
            return this.actionsField;
        }
        set {
            this.actionsField = value;
        }
    }
    
    /// <remarks/>
    public LinkDrawingInformation drawingInformation {
        get {
            return this.drawingInformationField;
        }
        set {
            this.drawingInformationField = value;
        }
    }
    
    /// <remarks/>
    public LinkGrammar grammar {
        get {
            return this.grammarField;
        }
        set {
            this.grammarField = value;
        }
    }
    
    /// <remarks/>
    public float strength {
        get {
            return this.strengthField;
        }
        set {
            this.strengthField = value;
        }
    }
    
    /// <remarks/>
    public string style {
        get {
            return this.styleField;
        }
        set {
            this.styleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string to {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string from {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="InformationConnectionsEngine.data")]
public partial class LinkDrawingInformation {
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="InformationConnectionsEngine.data")]
public partial class LinkGrammar {
    
    private string verbField;
    
    private string complementField;
    
    /// <remarks/>
    public string verb {
        get {
            return this.verbField;
        }
        set {
            this.verbField = value;
        }
    }
    
    /// <remarks/>
    public string complement {
        get {
            return this.complementField;
        }
        set {
            this.complementField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="InformationConnectionsEngine.data")]
public partial class NodeDrawingInformation {
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}
