ALTER TABLE [dbo].[Job.Approval]
    ADD CONSTRAINT [PK_JobApproval] PRIMARY KEY CLUSTERED ([JobApprovalId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

