ALTER TABLE [dbo].[Profile.Work]
    ADD CONSTRAINT [PK_ProfileWork] PRIMARY KEY CLUSTERED ([ProfileWorkId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

