ALTER TABLE [dbo].[Profile.Basic]
    ADD CONSTRAINT [PK_ProfileBasic] PRIMARY KEY CLUSTERED ([ProfileBasicId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

