//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobZoom.Web.JobZoomServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JobZoomServiceReference.IJobZoomService")]
    public interface IJobZoomService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/ValidateUser", ReplyAction="http://tempuri.org/IJobZoomService/ValidateUserResponse")]
        bool ValidateUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/GetProfileBasicByUserId", ReplyAction="http://tempuri.org/IJobZoomService/GetProfileBasicByUserIdResponse")]
        JobZoom.Business.Entities.Profile_Basic GetProfileBasicByUserId(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/SaveProfileBasic", ReplyAction="http://tempuri.org/IJobZoomService/SaveProfileBasicResponse")]
        void SaveProfileBasic(JobZoom.Business.Entities.Profile_Basic profile_basic);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJobZoomServiceChannel : JobZoom.Web.JobZoomServiceReference.IJobZoomService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobZoomServiceClient : System.ServiceModel.ClientBase<JobZoom.Web.JobZoomServiceReference.IJobZoomService>, JobZoom.Web.JobZoomServiceReference.IJobZoomService {
        
        public JobZoomServiceClient() {
        }
        
        public JobZoomServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobZoomServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobZoomServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobZoomServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidateUser(string username, string password) {
            return base.Channel.ValidateUser(username, password);
        }
        
        public JobZoom.Business.Entities.Profile_Basic GetProfileBasicByUserId(string userId) {
            return base.Channel.GetProfileBasicByUserId(userId);
        }
        
        public void SaveProfileBasic(JobZoom.Business.Entities.Profile_Basic profile_basic) {
            base.Channel.SaveProfileBasic(profile_basic);
        }
    }
}
