//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobZoom.Web.JobZoomServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/JobZoom.Services")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JobZoomServiceReference.IJobZoomService")]
    public interface IJobZoomService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/GetData", ReplyAction="http://tempuri.org/IJobZoomService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IJobZoomService/GetDataUsingDataContractResponse")]
        JobZoom.Web.JobZoomServiceReference.CompositeType GetDataUsingDataContract(JobZoom.Web.JobZoomServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/GetAllCountries", ReplyAction="http://tempuri.org/IJobZoomService/GetAllCountriesResponse")]
        System.Collections.Generic.List<JobZoom.Business.Entites.Country> GetAllCountries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/GetAllCities", ReplyAction="http://tempuri.org/IJobZoomService/GetAllCitiesResponse")]
        System.Collections.Generic.List<JobZoom.Business.Entites.City> GetAllCities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/GetAllIndustries", ReplyAction="http://tempuri.org/IJobZoomService/GetAllIndustriesResponse")]
        System.Collections.Generic.List<JobZoom.Business.Entites.Industry> GetAllIndustries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/GetAllFunctions", ReplyAction="http://tempuri.org/IJobZoomService/GetAllFunctionsResponse")]
        System.Collections.Generic.List<JobZoom.Business.Entites.Function> GetAllFunctions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/GetJobseeker", ReplyAction="http://tempuri.org/IJobZoomService/GetJobseekerResponse")]
        JobZoom.Business.Entites.Jobseeker GetJobseeker(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/SavePersonalInfo", ReplyAction="http://tempuri.org/IJobZoomService/SavePersonalInfoResponse")]
        bool SavePersonalInfo(JobZoom.Business.Entites.Jobseeker model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/GetExperience", ReplyAction="http://tempuri.org/IJobZoomService/GetExperienceResponse")]
        JobZoom.Business.Entites.Jobseeker_Experience GetExperience(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/GetAllEducation", ReplyAction="http://tempuri.org/IJobZoomService/GetAllEducationResponse")]
        System.Collections.Generic.List<JobZoom.Business.Entites.Jobseeker_Experience> GetAllEducation(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/GetAllExperience", ReplyAction="http://tempuri.org/IJobZoomService/GetAllExperienceResponse")]
        System.Collections.Generic.List<JobZoom.Business.Entites.Jobseeker_Experience> GetAllExperience(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/AddEducation", ReplyAction="http://tempuri.org/IJobZoomService/AddEducationResponse")]
        bool AddEducation(JobZoom.Business.Entites.Jobseeker_Experience model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/AddWorkExperience", ReplyAction="http://tempuri.org/IJobZoomService/AddWorkExperienceResponse")]
        bool AddWorkExperience(JobZoom.Business.Entites.Jobseeker_Experience model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/SaveExperience", ReplyAction="http://tempuri.org/IJobZoomService/SaveExperienceResponse")]
        bool SaveExperience(JobZoom.Business.Entites.Jobseeker_Experience model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/DeleteExperience", ReplyAction="http://tempuri.org/IJobZoomService/DeleteExperienceResponse")]
        bool DeleteExperience(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/GetAllSkill", ReplyAction="http://tempuri.org/IJobZoomService/GetAllSkillResponse")]
        System.Collections.Generic.List<JobZoom.Business.Entites.Jobseeker_Skill> GetAllSkill(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/AddSkill", ReplyAction="http://tempuri.org/IJobZoomService/AddSkillResponse")]
        bool AddSkill(JobZoom.Business.Entites.Jobseeker_Skill model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/DeleteSkill", ReplyAction="http://tempuri.org/IJobZoomService/DeleteSkillResponse")]
        bool DeleteSkill(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/GetAllHonorAward", ReplyAction="http://tempuri.org/IJobZoomService/GetAllHonorAwardResponse")]
        System.Collections.Generic.List<JobZoom.Business.Entites.Jobseeker_HonorAward> GetAllHonorAward(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/GetHonorAward", ReplyAction="http://tempuri.org/IJobZoomService/GetHonorAwardResponse")]
        JobZoom.Business.Entites.Jobseeker_HonorAward GetHonorAward(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/AddHonorAward", ReplyAction="http://tempuri.org/IJobZoomService/AddHonorAwardResponse")]
        bool AddHonorAward(JobZoom.Business.Entites.Jobseeker_HonorAward model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/SaveHonorAward", ReplyAction="http://tempuri.org/IJobZoomService/SaveHonorAwardResponse")]
        bool SaveHonorAward(JobZoom.Business.Entites.Jobseeker_HonorAward model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/DeleteHonorAward", ReplyAction="http://tempuri.org/IJobZoomService/DeleteHonorAwardResponse")]
        bool DeleteHonorAward(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/GetAllProject", ReplyAction="http://tempuri.org/IJobZoomService/GetAllProjectResponse")]
        System.Collections.Generic.List<JobZoom.Business.Entites.Jobseeker_Project> GetAllProject(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/GetProject", ReplyAction="http://tempuri.org/IJobZoomService/GetProjectResponse")]
        JobZoom.Business.Entites.Jobseeker_Project GetProject(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/AddProject", ReplyAction="http://tempuri.org/IJobZoomService/AddProjectResponse")]
        bool AddProject(JobZoom.Business.Entites.Jobseeker_Project model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/SaveProject", ReplyAction="http://tempuri.org/IJobZoomService/SaveProjectResponse")]
        bool SaveProject(JobZoom.Business.Entites.Jobseeker_Project model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobZoomService/DeleteProject", ReplyAction="http://tempuri.org/IJobZoomService/DeleteProjectResponse")]
        bool DeleteProject(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJobZoomServiceChannel : JobZoom.Web.JobZoomServiceReference.IJobZoomService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobZoomServiceClient : System.ServiceModel.ClientBase<JobZoom.Web.JobZoomServiceReference.IJobZoomService>, JobZoom.Web.JobZoomServiceReference.IJobZoomService {
        
        public JobZoomServiceClient() {
        }
        
        public JobZoomServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobZoomServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobZoomServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobZoomServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public JobZoom.Web.JobZoomServiceReference.CompositeType GetDataUsingDataContract(JobZoom.Web.JobZoomServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Collections.Generic.List<JobZoom.Business.Entites.Country> GetAllCountries() {
            return base.Channel.GetAllCountries();
        }
        
        public System.Collections.Generic.List<JobZoom.Business.Entites.City> GetAllCities() {
            return base.Channel.GetAllCities();
        }
        
        public System.Collections.Generic.List<JobZoom.Business.Entites.Industry> GetAllIndustries() {
            return base.Channel.GetAllIndustries();
        }
        
        public System.Collections.Generic.List<JobZoom.Business.Entites.Function> GetAllFunctions() {
            return base.Channel.GetAllFunctions();
        }
        
        public JobZoom.Business.Entites.Jobseeker GetJobseeker(string userID) {
            return base.Channel.GetJobseeker(userID);
        }
        
        public bool SavePersonalInfo(JobZoom.Business.Entites.Jobseeker model) {
            return base.Channel.SavePersonalInfo(model);
        }
        
        public JobZoom.Business.Entites.Jobseeker_Experience GetExperience(string id) {
            return base.Channel.GetExperience(id);
        }
        
        public System.Collections.Generic.List<JobZoom.Business.Entites.Jobseeker_Experience> GetAllEducation(string userID) {
            return base.Channel.GetAllEducation(userID);
        }
        
        public System.Collections.Generic.List<JobZoom.Business.Entites.Jobseeker_Experience> GetAllExperience(string userID) {
            return base.Channel.GetAllExperience(userID);
        }
        
        public bool AddEducation(JobZoom.Business.Entites.Jobseeker_Experience model) {
            return base.Channel.AddEducation(model);
        }
        
        public bool AddWorkExperience(JobZoom.Business.Entites.Jobseeker_Experience model) {
            return base.Channel.AddWorkExperience(model);
        }
        
        public bool SaveExperience(JobZoom.Business.Entites.Jobseeker_Experience model) {
            return base.Channel.SaveExperience(model);
        }
        
        public bool DeleteExperience(string id) {
            return base.Channel.DeleteExperience(id);
        }
        
        public System.Collections.Generic.List<JobZoom.Business.Entites.Jobseeker_Skill> GetAllSkill(string userID) {
            return base.Channel.GetAllSkill(userID);
        }
        
        public bool AddSkill(JobZoom.Business.Entites.Jobseeker_Skill model) {
            return base.Channel.AddSkill(model);
        }
        
        public bool DeleteSkill(string id) {
            return base.Channel.DeleteSkill(id);
        }
        
        public System.Collections.Generic.List<JobZoom.Business.Entites.Jobseeker_HonorAward> GetAllHonorAward(string userID) {
            return base.Channel.GetAllHonorAward(userID);
        }
        
        public JobZoom.Business.Entites.Jobseeker_HonorAward GetHonorAward(string id) {
            return base.Channel.GetHonorAward(id);
        }
        
        public bool AddHonorAward(JobZoom.Business.Entites.Jobseeker_HonorAward model) {
            return base.Channel.AddHonorAward(model);
        }
        
        public bool SaveHonorAward(JobZoom.Business.Entites.Jobseeker_HonorAward model) {
            return base.Channel.SaveHonorAward(model);
        }
        
        public bool DeleteHonorAward(string id) {
            return base.Channel.DeleteHonorAward(id);
        }
        
        public System.Collections.Generic.List<JobZoom.Business.Entites.Jobseeker_Project> GetAllProject(string userID) {
            return base.Channel.GetAllProject(userID);
        }
        
        public JobZoom.Business.Entites.Jobseeker_Project GetProject(string id) {
            return base.Channel.GetProject(id);
        }
        
        public bool AddProject(JobZoom.Business.Entites.Jobseeker_Project model) {
            return base.Channel.AddProject(model);
        }
        
        public bool SaveProject(JobZoom.Business.Entites.Jobseeker_Project model) {
            return base.Channel.SaveProject(model);
        }
        
        public bool DeleteProject(string id) {
            return base.Channel.DeleteProject(id);
        }
    }
}
