//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFramework.Console
{
    using System;
    using System.Collections.Generic;
    using JobZoom.Core.Entities;
    using JobZoom.Core.FlexibleAttributes;
    
    [TagContract]
    public partial class Profile_Basic
    {
        public System.Guid ProfileBasicId { get; set; }
        public string UserId { get; set; }

        [TagMember(TaggingType = TaggingType.ColumnNameAsTag)]
        public string FirstName { get; set; }

        [TagMember(TaggingType = TaggingType.ColumnNameAsTag)]
        public string LastName { get; set; }

        [TagMember(TaggingType = TaggingType.ColumnNameAsTag)]
        public string Gender { get; set; }

        [TagMember(TaggingType = TaggingType.ColumnNameAsTag)]
        public System.DateTime Birthdate { get; set; }

        [TagMember(TaggingType = TaggingType.ColumnNameAsTag)]
        public string MaritalStatus { get; set; }        
        public string ProfilePictureUrl { get; set; }

        [TagMember(TaggingType = TaggingType.ValueAsTag)]
        public string AddressLine1 { get; set; }

        [TagMember(TaggingType = TaggingType.ValueAsTag)]
        public string AddressLine2 { get; set; }

        [TagMember(TaggingType = TaggingType.ValueAsTag)]
        public string Country { get; set; }

        [TagMember(TaggingType = TaggingType.ValueAsTag)]
        public string City { get; set; }
        
        public Nullable<int> ZipCode { get; set; }
        
        public string Phone { get; set; }
        
        public string MobilePhone { get; set; }
        
        public string Website { get; set; }
        
        public string Facebook { get; set; }
        
        public string Twitter { get; set; }
    }
}
