//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFramework.Console
{
    using System;
    using System.Collections.Generic;
    using JobZoom.Core.FlexibleAttributes;
    
    [TagContract]
    public partial class Profile_Education
    {
        public System.Guid ProfileEducationId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.Guid> SchoolUniversityId { get; set; }

        [TagMember(TaggingType = TaggingType.ColumnNameAsTag)]
        public string SchoolUniversityName { get; set; }

        [TagMember(TaggingType = TaggingType.ColumnNameAsTag)]
        public string Major { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> CurrentlyLearn { get; set; }
        public string Description { get; set; }
    }
}
