//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFramework.Console
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestFrameworkEntities : DbContext
    {
        public TestFrameworkEntities()
            : base("name=TestFrameworkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Job_EducationExpRequirement> Job_EducationExpRequirement { get; set; }
        public DbSet<Job_OtherRequirement> Job_OtherRequirement { get; set; }
        public DbSet<Job_Posting> Job_Posting { get; set; }
        public DbSet<Job_WorkExpRequirement> Job_WorkExpRequirement { get; set; }
        public DbSet<Profile_Basic> Profile_Basic { get; set; }
        public DbSet<Profile_Education> Profile_Education { get; set; }
        public DbSet<Profile_Work> Profile_Work { get; set; }
    }
}
