CREATE TABLE [dbo].[User] (
    [UserId] [nvarchar](128) NOT NULL,
	[Email] [nvarchar](128) NOT NULL,
	[Password] [nvarchar](128) NOT NULL,
	[PasswordSalt] [nvarchar](128) NOT NULL,
	[Comments] [nvarchar](256) NULL,
	[CreatedDate] [datetime] NOT NULL,
	[LastModifiedDate] [datetime] NULL,
	[LastLoginDate] [datetime] NOT NULL,
	[LastLoginIP] [nvarchar](40) NULL,
	[IsActivated] [bit] NOT NULL,
	[IsLockedOut] [bit] NOT NULL,
	[IsOnline] [bit] NULL,
	[LastLockedOutDate] [datetime] NOT NULL,
	[LastLockedOutReason] [nvarchar](256) NULL,
	[LastPasswordChangedDate] [datetime] NOT NULL,
	[LastActivityDate] [datetime] NOT NULL,
	[NewPasswordKey] [nvarchar](128) NULL,
	[NewPasswordRequested] [datetime] NULL,
	[NewEmail] [nvarchar](128) NULL,
	[NewEmailKey] [nvarchar](128) NULL,
	[NewEmailRequested] [datetime] NULL,
);