-- =============================================
-- Table Industry
-- =============================================
INSERT INTO Industry(Name) VALUES('Accounting');
INSERT INTO Industry(Name) VALUES('Airlines/Aviation');
INSERT INTO Industry(Name) VALUES('Alternative Dispute Resolution');
INSERT INTO Industry(Name) VALUES('Alternative Medicine');
INSERT INTO Industry(Name) VALUES('Animation');
INSERT INTO Industry(Name) VALUES('Apparel & Fashion');
INSERT INTO Industry(Name) VALUES('Architecture & Planning');
INSERT INTO Industry(Name) VALUES('Arts and Crafts');
INSERT INTO Industry(Name) VALUES('Automotive');
INSERT INTO Industry(Name) VALUES('Aviation & Aerospace');
INSERT INTO Industry(Name) VALUES('Banking');
INSERT INTO Industry(Name) VALUES('Biotechnology');
INSERT INTO Industry(Name) VALUES('Broadcast Media');
INSERT INTO Industry(Name) VALUES('Building Materials');
INSERT INTO Industry(Name) VALUES('Business Supplies and Equipment');
INSERT INTO Industry(Name) VALUES('Capital Markets');
INSERT INTO Industry(Name) VALUES('Chemicals');
INSERT INTO Industry(Name) VALUES('Civic & Social Organization');
INSERT INTO Industry(Name) VALUES('Civil Engineering');
INSERT INTO Industry(Name) VALUES('Commercial Real Estate');
INSERT INTO Industry(Name) VALUES('Computer & Network Security');
INSERT INTO Industry(Name) VALUES('Computer Games');
INSERT INTO Industry(Name) VALUES('Computer Hardware');
INSERT INTO Industry(Name) VALUES('Computer Networking');
INSERT INTO Industry(Name) VALUES('Computer Software');
INSERT INTO Industry(Name) VALUES('Construction');
INSERT INTO Industry(Name) VALUES('Consumer Electronics');
INSERT INTO Industry(Name) VALUES('Consumer Goods');
INSERT INTO Industry(Name) VALUES('Consumer Services');
INSERT INTO Industry(Name) VALUES('Cosmetics');
INSERT INTO Industry(Name) VALUES('Dairy');
INSERT INTO Industry(Name) VALUES('Defense & Space');
INSERT INTO Industry(Name) VALUES('Design');
INSERT INTO Industry(Name) VALUES('Education Management');
INSERT INTO Industry(Name) VALUES('E-Learning');
INSERT INTO Industry(Name) VALUES('Electrical/Electronic Manufacturing');
INSERT INTO Industry(Name) VALUES('Entertainment');
INSERT INTO Industry(Name) VALUES('Environmental Services');
INSERT INTO Industry(Name) VALUES('Events Services');
INSERT INTO Industry(Name) VALUES('Executive Office');
INSERT INTO Industry(Name) VALUES('Facilities Services');
INSERT INTO Industry(Name) VALUES('Farming');
INSERT INTO Industry(Name) VALUES('Financial Services');
INSERT INTO Industry(Name) VALUES('Fine Art');
INSERT INTO Industry(Name) VALUES('Fishery');
INSERT INTO Industry(Name) VALUES('Food & Beverages');
INSERT INTO Industry(Name) VALUES('Food Production');
INSERT INTO Industry(Name) VALUES('Fund-Raising');
INSERT INTO Industry(Name) VALUES('Furniture');
INSERT INTO Industry(Name) VALUES('Gambling & Casinos');
INSERT INTO Industry(Name) VALUES('Glass, Ceramics & Concrete');
INSERT INTO Industry(Name) VALUES('Government Administration');
INSERT INTO Industry(Name) VALUES('Government Relations');
INSERT INTO Industry(Name) VALUES('Graphic Design');
INSERT INTO Industry(Name) VALUES('Health, Wellness and Fitness');
INSERT INTO Industry(Name) VALUES('Higher Education');
INSERT INTO Industry(Name) VALUES('Hospital & Health Care');
INSERT INTO Industry(Name) VALUES('Hospitality');
INSERT INTO Industry(Name) VALUES('Human Resources');
INSERT INTO Industry(Name) VALUES('Import and Export');
INSERT INTO Industry(Name) VALUES('Individual & Family Services');
INSERT INTO Industry(Name) VALUES('Industrial Automation');
INSERT INTO Industry(Name) VALUES('Information Services');
INSERT INTO Industry(Name) VALUES('Information Technology and Services');
INSERT INTO Industry(Name) VALUES('Insurance');
INSERT INTO Industry(Name) VALUES('International Affairs');
INSERT INTO Industry(Name) VALUES('International Trade and Development');
INSERT INTO Industry(Name) VALUES('Internet');
INSERT INTO Industry(Name) VALUES('Investment Banking');
INSERT INTO Industry(Name) VALUES('Investment Management');
INSERT INTO Industry(Name) VALUES('Judiciary');
INSERT INTO Industry(Name) VALUES('Law Enforcement');
INSERT INTO Industry(Name) VALUES('Law Practice');
INSERT INTO Industry(Name) VALUES('Legal Services');
INSERT INTO Industry(Name) VALUES('Legislative Office');
INSERT INTO Industry(Name) VALUES('Leisure, Travel & Tourism');
INSERT INTO Industry(Name) VALUES('Libraries');
INSERT INTO Industry(Name) VALUES('Logistics and Supply Chain');
INSERT INTO Industry(Name) VALUES('Luxury Goods & Jewelry');
INSERT INTO Industry(Name) VALUES('Machinery');
INSERT INTO Industry(Name) VALUES('Management Consulting');
INSERT INTO Industry(Name) VALUES('Maritime');
INSERT INTO Industry(Name) VALUES('Marketing and Advertising');
INSERT INTO Industry(Name) VALUES('Market Research');
INSERT INTO Industry(Name) VALUES('Mechanical or Industrial Engineering');
INSERT INTO Industry(Name) VALUES('Media Production');
INSERT INTO Industry(Name) VALUES('Medical Devices');
INSERT INTO Industry(Name) VALUES('Medical Practice');
INSERT INTO Industry(Name) VALUES('Mental Health Care');
INSERT INTO Industry(Name) VALUES('Military');
INSERT INTO Industry(Name) VALUES('Mining & Metals');
INSERT INTO Industry(Name) VALUES('Motion Pictures and Film');
INSERT INTO Industry(Name) VALUES('Museums and Institutions');
INSERT INTO Industry(Name) VALUES('Music');
INSERT INTO Industry(Name) VALUES('Nanotechnology');
INSERT INTO Industry(Name) VALUES('Newspapers');
INSERT INTO Industry(Name) VALUES('Nonprofit Organization Management');
INSERT INTO Industry(Name) VALUES('Oil & Energy');
INSERT INTO Industry(Name) VALUES('Online Media');
INSERT INTO Industry(Name) VALUES('Outsourcing/Offshoring');
INSERT INTO Industry(Name) VALUES('Package/Freight Delivery');
INSERT INTO Industry(Name) VALUES('Packaging and Containers');
INSERT INTO Industry(Name) VALUES('Paper & Forest Products');
INSERT INTO Industry(Name) VALUES('Performing Arts');
INSERT INTO Industry(Name) VALUES('Pharmaceuticals');
INSERT INTO Industry(Name) VALUES('Philanthropy');
INSERT INTO Industry(Name) VALUES('Photography');
INSERT INTO Industry(Name) VALUES('Plastics');
INSERT INTO Industry(Name) VALUES('Political Organization');
INSERT INTO Industry(Name) VALUES('Primary/Secondary Education');
INSERT INTO Industry(Name) VALUES('Printing');
INSERT INTO Industry(Name) VALUES('Professional Training & Coaching');
INSERT INTO Industry(Name) VALUES('Program Development');
INSERT INTO Industry(Name) VALUES('Public Policy');
INSERT INTO Industry(Name) VALUES('Public Relations and Communications');
INSERT INTO Industry(Name) VALUES('Public Safety');
INSERT INTO Industry(Name) VALUES('Publishing');
INSERT INTO Industry(Name) VALUES('Railroad Manufacture');
INSERT INTO Industry(Name) VALUES('Ranching');
INSERT INTO Industry(Name) VALUES('Real Estate');
INSERT INTO Industry(Name) VALUES('Recreational Facilities and Services');
INSERT INTO Industry(Name) VALUES('Religious Institutions');
INSERT INTO Industry(Name) VALUES('Renewables & Environment');
INSERT INTO Industry(Name) VALUES('Research');
INSERT INTO Industry(Name) VALUES('Restaurants');
INSERT INTO Industry(Name) VALUES('Retail');
INSERT INTO Industry(Name) VALUES('Security and Investigations');
INSERT INTO Industry(Name) VALUES('Semiconductors');
INSERT INTO Industry(Name) VALUES('Shipbuilding');
INSERT INTO Industry(Name) VALUES('Sporting Goods');
INSERT INTO Industry(Name) VALUES('Sports');
INSERT INTO Industry(Name) VALUES('Staffing and Recruiting');
INSERT INTO Industry(Name) VALUES('Supermarkets');
INSERT INTO Industry(Name) VALUES('Telecommunications');
INSERT INTO Industry(Name) VALUES('Textiles');
INSERT INTO Industry(Name) VALUES('Think Tanks');
INSERT INTO Industry(Name) VALUES('Tobacco');
INSERT INTO Industry(Name) VALUES('Translation and Localization');
INSERT INTO Industry(Name) VALUES('Transportation/Trucking/Railroad');
INSERT INTO Industry(Name) VALUES('Utilities');
INSERT INTO Industry(Name) VALUES('Venture Capital & Private Equity');
INSERT INTO Industry(Name) VALUES('Veterinary');
INSERT INTO Industry(Name) VALUES('Warehousing');
INSERT INTO Industry(Name) VALUES('Wholesale');
INSERT INTO Industry(Name) VALUES('Wine and Spirits');
INSERT INTO Industry(Name) VALUES('Wireless');
INSERT INTO Industry(Name) VALUES('Writing and Editing');

-- =============================================
-- Table Function
-- =============================================
INSERT INTO [Function](ID, Name) VALUES('acct', 'Accounting/Auditing');
INSERT INTO [Function](ID, Name) VALUES('adm', 'Administrative');
INSERT INTO [Function](ID, Name) VALUES('advr', 'Advertising');
INSERT INTO [Function](ID, Name) VALUES('anls', 'Analyst');
INSERT INTO [Function](ID, Name) VALUES('art', 'Art/Creative');
INSERT INTO [Function](ID, Name) VALUES('bd', 'Business Development');
INSERT INTO [Function](ID, Name) VALUES('cnsl', 'Consulting');
INSERT INTO [Function](ID, Name) VALUES('cust', 'Customer Service');
INSERT INTO [Function](ID, Name) VALUES('dsgn', 'Design');
INSERT INTO [Function](ID, Name) VALUES('dist', 'Distribution');
INSERT INTO [Function](ID, Name) VALUES('edu', 'Education');
INSERT INTO [Function](ID, Name) VALUES('eng', 'Engineering');
INSERT INTO [Function](ID, Name) VALUES('fin', 'Finance');
INSERT INTO [Function](ID, Name) VALUES('genb', 'General Business');
INSERT INTO [Function](ID, Name) VALUES('hcpr', 'Health Care Provider');
INSERT INTO [Function](ID, Name) VALUES('hr', 'Human Resources');
INSERT INTO [Function](ID, Name) VALUES('it', 'Information Technology');
INSERT INTO [Function](ID, Name) VALUES('lgl', 'Legal');
INSERT INTO [Function](ID, Name) VALUES('mgmt', 'Management');
INSERT INTO [Function](ID, Name) VALUES('mnfc', 'Manufacturing');
INSERT INTO [Function](ID, Name) VALUES('mrkt', 'Marketing');
INSERT INTO [Function](ID, Name) VALUES('prod', 'Production');
INSERT INTO [Function](ID, Name) VALUES('prdm', 'Product Management');
INSERT INTO [Function](ID, Name) VALUES('prjm', 'Project Management');
INSERT INTO [Function](ID, Name) VALUES('pr', 'Public Relations');
INSERT INTO [Function](ID, Name) VALUES('prch', 'Purchasing');
INSERT INTO [Function](ID, Name) VALUES('qa', 'Quality Assurance');
INSERT INTO [Function](ID, Name) VALUES('rsch', 'Research');
INSERT INTO [Function](ID, Name) VALUES('sale', 'Sales');
INSERT INTO [Function](ID, Name) VALUES('sci', 'Science');
INSERT INTO [Function](ID, Name) VALUES('stra', 'Strategy/Planning');
INSERT INTO [Function](ID, Name) VALUES('supl', 'Supply Chain');
INSERT INTO [Function](ID, Name) VALUES('trng', 'Training');
INSERT INTO [Function](ID, Name) VALUES('wrt', 'Writing/Editing');
INSERT INTO [Function](ID, Name) VALUES('othr', 'Other');
