//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CoreModel", "FK_Node_NodeDistribution", "DecisionTreeNode", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DecisionTreeDataStructure.DecisionTreeNode), "DecisionTreeNodeDistribution", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DecisionTreeDataStructure.DecisionTreeNodeDistribution), true)]
[assembly: EdmRelationshipAttribute("CoreModel", "FK_ParentNode_Node", "DecisionTreeNode", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DecisionTreeDataStructure.DecisionTreeNode), "DecisionTreeNode1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DecisionTreeDataStructure.DecisionTreeNode), true)]

#endregion

namespace DecisionTreeDataStructure
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CoreEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CoreEntities object using the connection string found in the 'CoreEntities' section of the application configuration file.
        /// </summary>
        public CoreEntities() : base("name=CoreEntities", "CoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CoreEntities object.
        /// </summary>
        public CoreEntities(string connectionString) : base(connectionString, "CoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CoreEntities object.
        /// </summary>
        public CoreEntities(EntityConnection connection) : base(connection, "CoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DecisionTreeNode> DecisionTreeNodes
        {
            get
            {
                if ((_DecisionTreeNodes == null))
                {
                    _DecisionTreeNodes = base.CreateObjectSet<DecisionTreeNode>("DecisionTreeNodes");
                }
                return _DecisionTreeNodes;
            }
        }
        private ObjectSet<DecisionTreeNode> _DecisionTreeNodes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DecisionTreeNodeDistribution> DecisionTreeNodeDistributions
        {
            get
            {
                if ((_DecisionTreeNodeDistributions == null))
                {
                    _DecisionTreeNodeDistributions = base.CreateObjectSet<DecisionTreeNodeDistribution>("DecisionTreeNodeDistributions");
                }
                return _DecisionTreeNodeDistributions;
            }
        }
        private ObjectSet<DecisionTreeNodeDistribution> _DecisionTreeNodeDistributions;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DecisionTreeNodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDecisionTreeNodes(DecisionTreeNode decisionTreeNode)
        {
            base.AddObject("DecisionTreeNodes", decisionTreeNode);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DecisionTreeNodeDistributions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDecisionTreeNodeDistributions(DecisionTreeNodeDistribution decisionTreeNodeDistribution)
        {
            base.AddObject("DecisionTreeNodeDistributions", decisionTreeNodeDistribution);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CoreModel", Name="DecisionTreeNode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DecisionTreeNode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DecisionTreeNode object.
        /// </summary>
        /// <param name="nODE_ID">Initial value of the NODE_ID property.</param>
        /// <param name="mODEL_NAME">Initial value of the MODEL_NAME property.</param>
        /// <param name="nODE_TYPE">Initial value of the NODE_TYPE property.</param>
        /// <param name="cHILDREN_CARDINALITY">Initial value of the CHILDREN_CARDINALITY property.</param>
        /// <param name="nODE_PROBABILITY">Initial value of the NODE_PROBABILITY property.</param>
        /// <param name="nODE_SUPPORT">Initial value of the NODE_SUPPORT property.</param>
        public static DecisionTreeNode CreateDecisionTreeNode(global::System.String nODE_ID, global::System.String mODEL_NAME, global::System.Int32 nODE_TYPE, global::System.Int32 cHILDREN_CARDINALITY, global::System.Double nODE_PROBABILITY, global::System.Double nODE_SUPPORT)
        {
            DecisionTreeNode decisionTreeNode = new DecisionTreeNode();
            decisionTreeNode.NODE_ID = nODE_ID;
            decisionTreeNode.MODEL_NAME = mODEL_NAME;
            decisionTreeNode.NODE_TYPE = nODE_TYPE;
            decisionTreeNode.CHILDREN_CARDINALITY = cHILDREN_CARDINALITY;
            decisionTreeNode.NODE_PROBABILITY = nODE_PROBABILITY;
            decisionTreeNode.NODE_SUPPORT = nODE_SUPPORT;
            return decisionTreeNode;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NODE_ID
        {
            get
            {
                return _NODE_ID;
            }
            set
            {
                if (_NODE_ID != value)
                {
                    OnNODE_IDChanging(value);
                    ReportPropertyChanging("NODE_ID");
                    _NODE_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("NODE_ID");
                    OnNODE_IDChanged();
                }
            }
        }
        private global::System.String _NODE_ID;
        partial void OnNODE_IDChanging(global::System.String value);
        partial void OnNODE_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MODEL_NAME
        {
            get
            {
                return _MODEL_NAME;
            }
            set
            {
                OnMODEL_NAMEChanging(value);
                ReportPropertyChanging("MODEL_NAME");
                _MODEL_NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MODEL_NAME");
                OnMODEL_NAMEChanged();
            }
        }
        private global::System.String _MODEL_NAME;
        partial void OnMODEL_NAMEChanging(global::System.String value);
        partial void OnMODEL_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NODE_TYPE
        {
            get
            {
                return _NODE_TYPE;
            }
            set
            {
                OnNODE_TYPEChanging(value);
                ReportPropertyChanging("NODE_TYPE");
                _NODE_TYPE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NODE_TYPE");
                OnNODE_TYPEChanged();
            }
        }
        private global::System.Int32 _NODE_TYPE;
        partial void OnNODE_TYPEChanging(global::System.Int32 value);
        partial void OnNODE_TYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NODE_CAPTION
        {
            get
            {
                return _NODE_CAPTION;
            }
            set
            {
                OnNODE_CAPTIONChanging(value);
                ReportPropertyChanging("NODE_CAPTION");
                _NODE_CAPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NODE_CAPTION");
                OnNODE_CAPTIONChanged();
            }
        }
        private global::System.String _NODE_CAPTION;
        partial void OnNODE_CAPTIONChanging(global::System.String value);
        partial void OnNODE_CAPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CHILDREN_CARDINALITY
        {
            get
            {
                return _CHILDREN_CARDINALITY;
            }
            set
            {
                OnCHILDREN_CARDINALITYChanging(value);
                ReportPropertyChanging("CHILDREN_CARDINALITY");
                _CHILDREN_CARDINALITY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CHILDREN_CARDINALITY");
                OnCHILDREN_CARDINALITYChanged();
            }
        }
        private global::System.Int32 _CHILDREN_CARDINALITY;
        partial void OnCHILDREN_CARDINALITYChanging(global::System.Int32 value);
        partial void OnCHILDREN_CARDINALITYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PARENT_ID
        {
            get
            {
                return _PARENT_ID;
            }
            set
            {
                OnPARENT_IDChanging(value);
                ReportPropertyChanging("PARENT_ID");
                _PARENT_ID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PARENT_ID");
                OnPARENT_IDChanged();
            }
        }
        private global::System.String _PARENT_ID;
        partial void OnPARENT_IDChanging(global::System.String value);
        partial void OnPARENT_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NODE_DESCRIPTION
        {
            get
            {
                return _NODE_DESCRIPTION;
            }
            set
            {
                OnNODE_DESCRIPTIONChanging(value);
                ReportPropertyChanging("NODE_DESCRIPTION");
                _NODE_DESCRIPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NODE_DESCRIPTION");
                OnNODE_DESCRIPTIONChanged();
            }
        }
        private global::System.String _NODE_DESCRIPTION;
        partial void OnNODE_DESCRIPTIONChanging(global::System.String value);
        partial void OnNODE_DESCRIPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NODE_RULE
        {
            get
            {
                return _NODE_RULE;
            }
            set
            {
                OnNODE_RULEChanging(value);
                ReportPropertyChanging("NODE_RULE");
                _NODE_RULE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NODE_RULE");
                OnNODE_RULEChanged();
            }
        }
        private global::System.String _NODE_RULE;
        partial void OnNODE_RULEChanging(global::System.String value);
        partial void OnNODE_RULEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MARGINAL_RULE
        {
            get
            {
                return _MARGINAL_RULE;
            }
            set
            {
                OnMARGINAL_RULEChanging(value);
                ReportPropertyChanging("MARGINAL_RULE");
                _MARGINAL_RULE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MARGINAL_RULE");
                OnMARGINAL_RULEChanged();
            }
        }
        private global::System.String _MARGINAL_RULE;
        partial void OnMARGINAL_RULEChanging(global::System.String value);
        partial void OnMARGINAL_RULEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double NODE_PROBABILITY
        {
            get
            {
                return _NODE_PROBABILITY;
            }
            set
            {
                OnNODE_PROBABILITYChanging(value);
                ReportPropertyChanging("NODE_PROBABILITY");
                _NODE_PROBABILITY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NODE_PROBABILITY");
                OnNODE_PROBABILITYChanged();
            }
        }
        private global::System.Double _NODE_PROBABILITY;
        partial void OnNODE_PROBABILITYChanging(global::System.Double value);
        partial void OnNODE_PROBABILITYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> MARGINAL_PROBABILITY
        {
            get
            {
                return _MARGINAL_PROBABILITY;
            }
            set
            {
                OnMARGINAL_PROBABILITYChanging(value);
                ReportPropertyChanging("MARGINAL_PROBABILITY");
                _MARGINAL_PROBABILITY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MARGINAL_PROBABILITY");
                OnMARGINAL_PROBABILITYChanged();
            }
        }
        private Nullable<global::System.Double> _MARGINAL_PROBABILITY;
        partial void OnMARGINAL_PROBABILITYChanging(Nullable<global::System.Double> value);
        partial void OnMARGINAL_PROBABILITYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double NODE_SUPPORT
        {
            get
            {
                return _NODE_SUPPORT;
            }
            set
            {
                OnNODE_SUPPORTChanging(value);
                ReportPropertyChanging("NODE_SUPPORT");
                _NODE_SUPPORT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NODE_SUPPORT");
                OnNODE_SUPPORTChanged();
            }
        }
        private global::System.Double _NODE_SUPPORT;
        partial void OnNODE_SUPPORTChanging(global::System.Double value);
        partial void OnNODE_SUPPORTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MSOLAP_MODEL_COLUMN
        {
            get
            {
                return _MSOLAP_MODEL_COLUMN;
            }
            set
            {
                OnMSOLAP_MODEL_COLUMNChanging(value);
                ReportPropertyChanging("MSOLAP_MODEL_COLUMN");
                _MSOLAP_MODEL_COLUMN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MSOLAP_MODEL_COLUMN");
                OnMSOLAP_MODEL_COLUMNChanged();
            }
        }
        private global::System.String _MSOLAP_MODEL_COLUMN;
        partial void OnMSOLAP_MODEL_COLUMNChanging(global::System.String value);
        partial void OnMSOLAP_MODEL_COLUMNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> MSOLAP_NODE_SCORE
        {
            get
            {
                return _MSOLAP_NODE_SCORE;
            }
            set
            {
                OnMSOLAP_NODE_SCOREChanging(value);
                ReportPropertyChanging("MSOLAP_NODE_SCORE");
                _MSOLAP_NODE_SCORE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MSOLAP_NODE_SCORE");
                OnMSOLAP_NODE_SCOREChanged();
            }
        }
        private Nullable<global::System.Double> _MSOLAP_NODE_SCORE;
        partial void OnMSOLAP_NODE_SCOREChanging(Nullable<global::System.Double> value);
        partial void OnMSOLAP_NODE_SCOREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MSOLAP_NODE_SHORT_CAPTION
        {
            get
            {
                return _MSOLAP_NODE_SHORT_CAPTION;
            }
            set
            {
                OnMSOLAP_NODE_SHORT_CAPTIONChanging(value);
                ReportPropertyChanging("MSOLAP_NODE_SHORT_CAPTION");
                _MSOLAP_NODE_SHORT_CAPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MSOLAP_NODE_SHORT_CAPTION");
                OnMSOLAP_NODE_SHORT_CAPTIONChanged();
            }
        }
        private global::System.String _MSOLAP_NODE_SHORT_CAPTION;
        partial void OnMSOLAP_NODE_SHORT_CAPTIONChanging(global::System.String value);
        partial void OnMSOLAP_NODE_SHORT_CAPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ATTRIBUTE_NAME
        {
            get
            {
                return _ATTRIBUTE_NAME;
            }
            set
            {
                OnATTRIBUTE_NAMEChanging(value);
                ReportPropertyChanging("ATTRIBUTE_NAME");
                _ATTRIBUTE_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ATTRIBUTE_NAME");
                OnATTRIBUTE_NAMEChanged();
            }
        }
        private global::System.String _ATTRIBUTE_NAME;
        partial void OnATTRIBUTE_NAMEChanging(global::System.String value);
        partial void OnATTRIBUTE_NAMEChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CoreModel", "FK_Node_NodeDistribution", "DecisionTreeNodeDistribution")]
        public EntityCollection<DecisionTreeNodeDistribution> DecisionTreeNodeDistributions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DecisionTreeNodeDistribution>("CoreModel.FK_Node_NodeDistribution", "DecisionTreeNodeDistribution");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DecisionTreeNodeDistribution>("CoreModel.FK_Node_NodeDistribution", "DecisionTreeNodeDistribution", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CoreModel", "FK_ParentNode_Node", "DecisionTreeNode1")]
        public EntityCollection<DecisionTreeNode> DecisionTreeNode_Childs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DecisionTreeNode>("CoreModel.FK_ParentNode_Node", "DecisionTreeNode1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DecisionTreeNode>("CoreModel.FK_ParentNode_Node", "DecisionTreeNode1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CoreModel", "FK_ParentNode_Node", "DecisionTreeNode")]
        public DecisionTreeNode DecisionTreeNode_Parent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DecisionTreeNode>("CoreModel.FK_ParentNode_Node", "DecisionTreeNode").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DecisionTreeNode>("CoreModel.FK_ParentNode_Node", "DecisionTreeNode").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DecisionTreeNode> DecisionTreeNode_ParentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DecisionTreeNode>("CoreModel.FK_ParentNode_Node", "DecisionTreeNode");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DecisionTreeNode>("CoreModel.FK_ParentNode_Node", "DecisionTreeNode", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CoreModel", Name="DecisionTreeNodeDistribution")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DecisionTreeNodeDistribution : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DecisionTreeNodeDistribution object.
        /// </summary>
        /// <param name="nODE_ID">Initial value of the NODE_ID property.</param>
        /// <param name="aTTRIBUTE_VALUE">Initial value of the ATTRIBUTE_VALUE property.</param>
        /// <param name="sUPPORT">Initial value of the SUPPORT property.</param>
        /// <param name="pROBABILITY">Initial value of the PROBABILITY property.</param>
        /// <param name="vARIANCE">Initial value of the VARIANCE property.</param>
        /// <param name="vALUETYPE">Initial value of the VALUETYPE property.</param>
        public static DecisionTreeNodeDistribution CreateDecisionTreeNodeDistribution(global::System.String nODE_ID, global::System.String aTTRIBUTE_VALUE, global::System.Double sUPPORT, global::System.Double pROBABILITY, global::System.Double vARIANCE, global::System.Int32 vALUETYPE)
        {
            DecisionTreeNodeDistribution decisionTreeNodeDistribution = new DecisionTreeNodeDistribution();
            decisionTreeNodeDistribution.NODE_ID = nODE_ID;
            decisionTreeNodeDistribution.ATTRIBUTE_VALUE = aTTRIBUTE_VALUE;
            decisionTreeNodeDistribution.SUPPORT = sUPPORT;
            decisionTreeNodeDistribution.PROBABILITY = pROBABILITY;
            decisionTreeNodeDistribution.VARIANCE = vARIANCE;
            decisionTreeNodeDistribution.VALUETYPE = vALUETYPE;
            return decisionTreeNodeDistribution;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NODE_ID
        {
            get
            {
                return _NODE_ID;
            }
            set
            {
                if (_NODE_ID != value)
                {
                    OnNODE_IDChanging(value);
                    ReportPropertyChanging("NODE_ID");
                    _NODE_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("NODE_ID");
                    OnNODE_IDChanged();
                }
            }
        }
        private global::System.String _NODE_ID;
        partial void OnNODE_IDChanging(global::System.String value);
        partial void OnNODE_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ATTRIBUTE_NAME
        {
            get
            {
                return _ATTRIBUTE_NAME;
            }
            set
            {
                OnATTRIBUTE_NAMEChanging(value);
                ReportPropertyChanging("ATTRIBUTE_NAME");
                _ATTRIBUTE_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ATTRIBUTE_NAME");
                OnATTRIBUTE_NAMEChanged();
            }
        }
        private global::System.String _ATTRIBUTE_NAME;
        partial void OnATTRIBUTE_NAMEChanging(global::System.String value);
        partial void OnATTRIBUTE_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ATTRIBUTE_VALUE
        {
            get
            {
                return _ATTRIBUTE_VALUE;
            }
            set
            {
                if (_ATTRIBUTE_VALUE != value)
                {
                    OnATTRIBUTE_VALUEChanging(value);
                    ReportPropertyChanging("ATTRIBUTE_VALUE");
                    _ATTRIBUTE_VALUE = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ATTRIBUTE_VALUE");
                    OnATTRIBUTE_VALUEChanged();
                }
            }
        }
        private global::System.String _ATTRIBUTE_VALUE;
        partial void OnATTRIBUTE_VALUEChanging(global::System.String value);
        partial void OnATTRIBUTE_VALUEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double SUPPORT
        {
            get
            {
                return _SUPPORT;
            }
            set
            {
                OnSUPPORTChanging(value);
                ReportPropertyChanging("SUPPORT");
                _SUPPORT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SUPPORT");
                OnSUPPORTChanged();
            }
        }
        private global::System.Double _SUPPORT;
        partial void OnSUPPORTChanging(global::System.Double value);
        partial void OnSUPPORTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double PROBABILITY
        {
            get
            {
                return _PROBABILITY;
            }
            set
            {
                OnPROBABILITYChanging(value);
                ReportPropertyChanging("PROBABILITY");
                _PROBABILITY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PROBABILITY");
                OnPROBABILITYChanged();
            }
        }
        private global::System.Double _PROBABILITY;
        partial void OnPROBABILITYChanging(global::System.Double value);
        partial void OnPROBABILITYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double VARIANCE
        {
            get
            {
                return _VARIANCE;
            }
            set
            {
                OnVARIANCEChanging(value);
                ReportPropertyChanging("VARIANCE");
                _VARIANCE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VARIANCE");
                OnVARIANCEChanged();
            }
        }
        private global::System.Double _VARIANCE;
        partial void OnVARIANCEChanging(global::System.Double value);
        partial void OnVARIANCEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VALUETYPE
        {
            get
            {
                return _VALUETYPE;
            }
            set
            {
                OnVALUETYPEChanging(value);
                ReportPropertyChanging("VALUETYPE");
                _VALUETYPE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VALUETYPE");
                OnVALUETYPEChanged();
            }
        }
        private global::System.Int32 _VALUETYPE;
        partial void OnVALUETYPEChanging(global::System.Int32 value);
        partial void OnVALUETYPEChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CoreModel", "FK_Node_NodeDistribution", "DecisionTreeNode")]
        public DecisionTreeNode DecisionTreeNode
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DecisionTreeNode>("CoreModel.FK_Node_NodeDistribution", "DecisionTreeNode").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DecisionTreeNode>("CoreModel.FK_Node_NodeDistribution", "DecisionTreeNode").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DecisionTreeNode> DecisionTreeNodeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DecisionTreeNode>("CoreModel.FK_Node_NodeDistribution", "DecisionTreeNode");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DecisionTreeNode>("CoreModel.FK_Node_NodeDistribution", "DecisionTreeNode", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
