//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("JobZoomCoreModel", "FK_Node_NodeDistribution", "DecisionTreeNode", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JobZoom.Core.Entities.DecisionTreeNode), "DecisionTreeNodeDistribution", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JobZoom.Core.Entities.DecisionTreeNodeDistribution), true)]
[assembly: EdmRelationshipAttribute("JobZoomCoreModel", "FK_ParentNode_Node", "DecisionTreeNode", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(JobZoom.Core.Entities.DecisionTreeNode), "DecisionTreeNode1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JobZoom.Core.Entities.DecisionTreeNode), true)]
[assembly: EdmRelationshipAttribute("JobZoomCoreModel", "FK_TagAttribute_TagAttribute", "TagAttribute", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(JobZoom.Core.Entities.TagAttribute), "TagAttribute1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JobZoom.Core.Entities.TagAttribute), true)]

#endregion

namespace JobZoom.Core.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class JobZoomCoreEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new JobZoomCoreEntities object using the connection string found in the 'JobZoomCoreEntities' section of the application configuration file.
        /// </summary>
        public JobZoomCoreEntities() : base("name=JobZoomCoreEntities", "JobZoomCoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new JobZoomCoreEntities object.
        /// </summary>
        public JobZoomCoreEntities(string connectionString) : base(connectionString, "JobZoomCoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new JobZoomCoreEntities object.
        /// </summary>
        public JobZoomCoreEntities(EntityConnection connection) : base(connection, "JobZoomCoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DecisionTreeNode> DecisionTreeNodes
        {
            get
            {
                if ((_DecisionTreeNodes == null))
                {
                    _DecisionTreeNodes = base.CreateObjectSet<DecisionTreeNode>("DecisionTreeNodes");
                }
                return _DecisionTreeNodes;
            }
        }
        private ObjectSet<DecisionTreeNode> _DecisionTreeNodes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DecisionTreeNodeDistribution> DecisionTreeNodeDistributions
        {
            get
            {
                if ((_DecisionTreeNodeDistributions == null))
                {
                    _DecisionTreeNodeDistributions = base.CreateObjectSet<DecisionTreeNodeDistribution>("DecisionTreeNodeDistributions");
                }
                return _DecisionTreeNodeDistributions;
            }
        }
        private ObjectSet<DecisionTreeNodeDistribution> _DecisionTreeNodeDistributions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SimilarityTerm> SimilarityTerms
        {
            get
            {
                if ((_SimilarityTerms == null))
                {
                    _SimilarityTerms = base.CreateObjectSet<SimilarityTerm>("SimilarityTerms");
                }
                return _SimilarityTerms;
            }
        }
        private ObjectSet<SimilarityTerm> _SimilarityTerms;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TagAttribute> TagAttributes
        {
            get
            {
                if ((_TagAttributes == null))
                {
                    _TagAttributes = base.CreateObjectSet<TagAttribute>("TagAttributes");
                }
                return _TagAttributes;
            }
        }
        private ObjectSet<TagAttribute> _TagAttributes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DecisionTreeNodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDecisionTreeNodes(DecisionTreeNode decisionTreeNode)
        {
            base.AddObject("DecisionTreeNodes", decisionTreeNode);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DecisionTreeNodeDistributions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDecisionTreeNodeDistributions(DecisionTreeNodeDistribution decisionTreeNodeDistribution)
        {
            base.AddObject("DecisionTreeNodeDistributions", decisionTreeNodeDistribution);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SimilarityTerms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSimilarityTerms(SimilarityTerm similarityTerm)
        {
            base.AddObject("SimilarityTerms", similarityTerm);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TagAttributes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTagAttributes(TagAttribute tagAttribute)
        {
            base.AddObject("TagAttributes", tagAttribute);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JobZoomCoreModel", Name="DecisionTreeNode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DecisionTreeNode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DecisionTreeNode object.
        /// </summary>
        /// <param name="nODE_ID">Initial value of the NODE_ID property.</param>
        /// <param name="mODEL_NAME">Initial value of the MODEL_NAME property.</param>
        /// <param name="nODE_TYPE">Initial value of the NODE_TYPE property.</param>
        /// <param name="cHILDREN_CARDINALITY">Initial value of the CHILDREN_CARDINALITY property.</param>
        /// <param name="nODE_PROBABILITY">Initial value of the NODE_PROBABILITY property.</param>
        /// <param name="nODE_SUPPORT">Initial value of the NODE_SUPPORT property.</param>
        public static DecisionTreeNode CreateDecisionTreeNode(global::System.String nODE_ID, global::System.String mODEL_NAME, global::System.Int32 nODE_TYPE, global::System.Int32 cHILDREN_CARDINALITY, global::System.Double nODE_PROBABILITY, global::System.Double nODE_SUPPORT)
        {
            DecisionTreeNode decisionTreeNode = new DecisionTreeNode();
            decisionTreeNode.NODE_ID = nODE_ID;
            decisionTreeNode.MODEL_NAME = mODEL_NAME;
            decisionTreeNode.NODE_TYPE = nODE_TYPE;
            decisionTreeNode.CHILDREN_CARDINALITY = cHILDREN_CARDINALITY;
            decisionTreeNode.NODE_PROBABILITY = nODE_PROBABILITY;
            decisionTreeNode.NODE_SUPPORT = nODE_SUPPORT;
            return decisionTreeNode;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NODE_ID
        {
            get
            {
                return _NODE_ID;
            }
            set
            {
                if (_NODE_ID != value)
                {
                    OnNODE_IDChanging(value);
                    ReportPropertyChanging("NODE_ID");
                    _NODE_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("NODE_ID");
                    OnNODE_IDChanged();
                }
            }
        }
        private global::System.String _NODE_ID;
        partial void OnNODE_IDChanging(global::System.String value);
        partial void OnNODE_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MODEL_NAME
        {
            get
            {
                return _MODEL_NAME;
            }
            set
            {
                OnMODEL_NAMEChanging(value);
                ReportPropertyChanging("MODEL_NAME");
                _MODEL_NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MODEL_NAME");
                OnMODEL_NAMEChanged();
            }
        }
        private global::System.String _MODEL_NAME;
        partial void OnMODEL_NAMEChanging(global::System.String value);
        partial void OnMODEL_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NODE_TYPE
        {
            get
            {
                return _NODE_TYPE;
            }
            set
            {
                OnNODE_TYPEChanging(value);
                ReportPropertyChanging("NODE_TYPE");
                _NODE_TYPE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NODE_TYPE");
                OnNODE_TYPEChanged();
            }
        }
        private global::System.Int32 _NODE_TYPE;
        partial void OnNODE_TYPEChanging(global::System.Int32 value);
        partial void OnNODE_TYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NODE_CAPTION
        {
            get
            {
                return _NODE_CAPTION;
            }
            set
            {
                OnNODE_CAPTIONChanging(value);
                ReportPropertyChanging("NODE_CAPTION");
                _NODE_CAPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NODE_CAPTION");
                OnNODE_CAPTIONChanged();
            }
        }
        private global::System.String _NODE_CAPTION;
        partial void OnNODE_CAPTIONChanging(global::System.String value);
        partial void OnNODE_CAPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CHILDREN_CARDINALITY
        {
            get
            {
                return _CHILDREN_CARDINALITY;
            }
            set
            {
                OnCHILDREN_CARDINALITYChanging(value);
                ReportPropertyChanging("CHILDREN_CARDINALITY");
                _CHILDREN_CARDINALITY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CHILDREN_CARDINALITY");
                OnCHILDREN_CARDINALITYChanged();
            }
        }
        private global::System.Int32 _CHILDREN_CARDINALITY;
        partial void OnCHILDREN_CARDINALITYChanging(global::System.Int32 value);
        partial void OnCHILDREN_CARDINALITYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PARENT_ID
        {
            get
            {
                return _PARENT_ID;
            }
            set
            {
                OnPARENT_IDChanging(value);
                ReportPropertyChanging("PARENT_ID");
                _PARENT_ID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PARENT_ID");
                OnPARENT_IDChanged();
            }
        }
        private global::System.String _PARENT_ID;
        partial void OnPARENT_IDChanging(global::System.String value);
        partial void OnPARENT_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NODE_DESCRIPTION
        {
            get
            {
                return _NODE_DESCRIPTION;
            }
            set
            {
                OnNODE_DESCRIPTIONChanging(value);
                ReportPropertyChanging("NODE_DESCRIPTION");
                _NODE_DESCRIPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NODE_DESCRIPTION");
                OnNODE_DESCRIPTIONChanged();
            }
        }
        private global::System.String _NODE_DESCRIPTION;
        partial void OnNODE_DESCRIPTIONChanging(global::System.String value);
        partial void OnNODE_DESCRIPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NODE_RULE
        {
            get
            {
                return _NODE_RULE;
            }
            set
            {
                OnNODE_RULEChanging(value);
                ReportPropertyChanging("NODE_RULE");
                _NODE_RULE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NODE_RULE");
                OnNODE_RULEChanged();
            }
        }
        private global::System.String _NODE_RULE;
        partial void OnNODE_RULEChanging(global::System.String value);
        partial void OnNODE_RULEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MARGINAL_RULE
        {
            get
            {
                return _MARGINAL_RULE;
            }
            set
            {
                OnMARGINAL_RULEChanging(value);
                ReportPropertyChanging("MARGINAL_RULE");
                _MARGINAL_RULE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MARGINAL_RULE");
                OnMARGINAL_RULEChanged();
            }
        }
        private global::System.String _MARGINAL_RULE;
        partial void OnMARGINAL_RULEChanging(global::System.String value);
        partial void OnMARGINAL_RULEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double NODE_PROBABILITY
        {
            get
            {
                return _NODE_PROBABILITY;
            }
            set
            {
                OnNODE_PROBABILITYChanging(value);
                ReportPropertyChanging("NODE_PROBABILITY");
                _NODE_PROBABILITY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NODE_PROBABILITY");
                OnNODE_PROBABILITYChanged();
            }
        }
        private global::System.Double _NODE_PROBABILITY;
        partial void OnNODE_PROBABILITYChanging(global::System.Double value);
        partial void OnNODE_PROBABILITYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> MARGINAL_PROBABILITY
        {
            get
            {
                return _MARGINAL_PROBABILITY;
            }
            set
            {
                OnMARGINAL_PROBABILITYChanging(value);
                ReportPropertyChanging("MARGINAL_PROBABILITY");
                _MARGINAL_PROBABILITY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MARGINAL_PROBABILITY");
                OnMARGINAL_PROBABILITYChanged();
            }
        }
        private Nullable<global::System.Double> _MARGINAL_PROBABILITY;
        partial void OnMARGINAL_PROBABILITYChanging(Nullable<global::System.Double> value);
        partial void OnMARGINAL_PROBABILITYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double NODE_SUPPORT
        {
            get
            {
                return _NODE_SUPPORT;
            }
            set
            {
                OnNODE_SUPPORTChanging(value);
                ReportPropertyChanging("NODE_SUPPORT");
                _NODE_SUPPORT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NODE_SUPPORT");
                OnNODE_SUPPORTChanged();
            }
        }
        private global::System.Double _NODE_SUPPORT;
        partial void OnNODE_SUPPORTChanging(global::System.Double value);
        partial void OnNODE_SUPPORTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MSOLAP_MODEL_COLUMN
        {
            get
            {
                return _MSOLAP_MODEL_COLUMN;
            }
            set
            {
                OnMSOLAP_MODEL_COLUMNChanging(value);
                ReportPropertyChanging("MSOLAP_MODEL_COLUMN");
                _MSOLAP_MODEL_COLUMN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MSOLAP_MODEL_COLUMN");
                OnMSOLAP_MODEL_COLUMNChanged();
            }
        }
        private global::System.String _MSOLAP_MODEL_COLUMN;
        partial void OnMSOLAP_MODEL_COLUMNChanging(global::System.String value);
        partial void OnMSOLAP_MODEL_COLUMNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> MSOLAP_NODE_SCORE
        {
            get
            {
                return _MSOLAP_NODE_SCORE;
            }
            set
            {
                OnMSOLAP_NODE_SCOREChanging(value);
                ReportPropertyChanging("MSOLAP_NODE_SCORE");
                _MSOLAP_NODE_SCORE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MSOLAP_NODE_SCORE");
                OnMSOLAP_NODE_SCOREChanged();
            }
        }
        private Nullable<global::System.Double> _MSOLAP_NODE_SCORE;
        partial void OnMSOLAP_NODE_SCOREChanging(Nullable<global::System.Double> value);
        partial void OnMSOLAP_NODE_SCOREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MSOLAP_NODE_SHORT_CAPTION
        {
            get
            {
                return _MSOLAP_NODE_SHORT_CAPTION;
            }
            set
            {
                OnMSOLAP_NODE_SHORT_CAPTIONChanging(value);
                ReportPropertyChanging("MSOLAP_NODE_SHORT_CAPTION");
                _MSOLAP_NODE_SHORT_CAPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MSOLAP_NODE_SHORT_CAPTION");
                OnMSOLAP_NODE_SHORT_CAPTIONChanged();
            }
        }
        private global::System.String _MSOLAP_NODE_SHORT_CAPTION;
        partial void OnMSOLAP_NODE_SHORT_CAPTIONChanging(global::System.String value);
        partial void OnMSOLAP_NODE_SHORT_CAPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ATTRIBUTE_NAME
        {
            get
            {
                return _ATTRIBUTE_NAME;
            }
            set
            {
                OnATTRIBUTE_NAMEChanging(value);
                ReportPropertyChanging("ATTRIBUTE_NAME");
                _ATTRIBUTE_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ATTRIBUTE_NAME");
                OnATTRIBUTE_NAMEChanged();
            }
        }
        private global::System.String _ATTRIBUTE_NAME;
        partial void OnATTRIBUTE_NAMEChanging(global::System.String value);
        partial void OnATTRIBUTE_NAMEChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JobZoomCoreModel", "FK_Node_NodeDistribution", "DecisionTreeNodeDistribution")]
        public EntityCollection<DecisionTreeNodeDistribution> DecisionTreeNodeDistributions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DecisionTreeNodeDistribution>("JobZoomCoreModel.FK_Node_NodeDistribution", "DecisionTreeNodeDistribution");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DecisionTreeNodeDistribution>("JobZoomCoreModel.FK_Node_NodeDistribution", "DecisionTreeNodeDistribution", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JobZoomCoreModel", "FK_ParentNode_Node", "DecisionTreeNode1")]
        public EntityCollection<DecisionTreeNode> DecisionTreeNode_Childs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DecisionTreeNode>("JobZoomCoreModel.FK_ParentNode_Node", "DecisionTreeNode1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DecisionTreeNode>("JobZoomCoreModel.FK_ParentNode_Node", "DecisionTreeNode1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JobZoomCoreModel", "FK_ParentNode_Node", "DecisionTreeNode")]
        public DecisionTreeNode DecisionTreeNode_Parent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DecisionTreeNode>("JobZoomCoreModel.FK_ParentNode_Node", "DecisionTreeNode").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DecisionTreeNode>("JobZoomCoreModel.FK_ParentNode_Node", "DecisionTreeNode").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DecisionTreeNode> DecisionTreeNode_ParentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DecisionTreeNode>("JobZoomCoreModel.FK_ParentNode_Node", "DecisionTreeNode");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DecisionTreeNode>("JobZoomCoreModel.FK_ParentNode_Node", "DecisionTreeNode", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JobZoomCoreModel", Name="DecisionTreeNodeDistribution")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DecisionTreeNodeDistribution : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DecisionTreeNodeDistribution object.
        /// </summary>
        /// <param name="nODE_ID">Initial value of the NODE_ID property.</param>
        /// <param name="aTTRIBUTE_VALUE">Initial value of the ATTRIBUTE_VALUE property.</param>
        /// <param name="sUPPORT">Initial value of the SUPPORT property.</param>
        /// <param name="pROBABILITY">Initial value of the PROBABILITY property.</param>
        /// <param name="vARIANCE">Initial value of the VARIANCE property.</param>
        /// <param name="vALUETYPE">Initial value of the VALUETYPE property.</param>
        public static DecisionTreeNodeDistribution CreateDecisionTreeNodeDistribution(global::System.String nODE_ID, global::System.String aTTRIBUTE_VALUE, global::System.Double sUPPORT, global::System.Double pROBABILITY, global::System.Double vARIANCE, global::System.Int32 vALUETYPE)
        {
            DecisionTreeNodeDistribution decisionTreeNodeDistribution = new DecisionTreeNodeDistribution();
            decisionTreeNodeDistribution.NODE_ID = nODE_ID;
            decisionTreeNodeDistribution.ATTRIBUTE_VALUE = aTTRIBUTE_VALUE;
            decisionTreeNodeDistribution.SUPPORT = sUPPORT;
            decisionTreeNodeDistribution.PROBABILITY = pROBABILITY;
            decisionTreeNodeDistribution.VARIANCE = vARIANCE;
            decisionTreeNodeDistribution.VALUETYPE = vALUETYPE;
            return decisionTreeNodeDistribution;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NODE_ID
        {
            get
            {
                return _NODE_ID;
            }
            set
            {
                if (_NODE_ID != value)
                {
                    OnNODE_IDChanging(value);
                    ReportPropertyChanging("NODE_ID");
                    _NODE_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("NODE_ID");
                    OnNODE_IDChanged();
                }
            }
        }
        private global::System.String _NODE_ID;
        partial void OnNODE_IDChanging(global::System.String value);
        partial void OnNODE_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ATTRIBUTE_NAME
        {
            get
            {
                return _ATTRIBUTE_NAME;
            }
            set
            {
                OnATTRIBUTE_NAMEChanging(value);
                ReportPropertyChanging("ATTRIBUTE_NAME");
                _ATTRIBUTE_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ATTRIBUTE_NAME");
                OnATTRIBUTE_NAMEChanged();
            }
        }
        private global::System.String _ATTRIBUTE_NAME;
        partial void OnATTRIBUTE_NAMEChanging(global::System.String value);
        partial void OnATTRIBUTE_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ATTRIBUTE_VALUE
        {
            get
            {
                return _ATTRIBUTE_VALUE;
            }
            set
            {
                if (_ATTRIBUTE_VALUE != value)
                {
                    OnATTRIBUTE_VALUEChanging(value);
                    ReportPropertyChanging("ATTRIBUTE_VALUE");
                    _ATTRIBUTE_VALUE = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ATTRIBUTE_VALUE");
                    OnATTRIBUTE_VALUEChanged();
                }
            }
        }
        private global::System.String _ATTRIBUTE_VALUE;
        partial void OnATTRIBUTE_VALUEChanging(global::System.String value);
        partial void OnATTRIBUTE_VALUEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double SUPPORT
        {
            get
            {
                return _SUPPORT;
            }
            set
            {
                OnSUPPORTChanging(value);
                ReportPropertyChanging("SUPPORT");
                _SUPPORT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SUPPORT");
                OnSUPPORTChanged();
            }
        }
        private global::System.Double _SUPPORT;
        partial void OnSUPPORTChanging(global::System.Double value);
        partial void OnSUPPORTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double PROBABILITY
        {
            get
            {
                return _PROBABILITY;
            }
            set
            {
                OnPROBABILITYChanging(value);
                ReportPropertyChanging("PROBABILITY");
                _PROBABILITY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PROBABILITY");
                OnPROBABILITYChanged();
            }
        }
        private global::System.Double _PROBABILITY;
        partial void OnPROBABILITYChanging(global::System.Double value);
        partial void OnPROBABILITYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double VARIANCE
        {
            get
            {
                return _VARIANCE;
            }
            set
            {
                OnVARIANCEChanging(value);
                ReportPropertyChanging("VARIANCE");
                _VARIANCE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VARIANCE");
                OnVARIANCEChanged();
            }
        }
        private global::System.Double _VARIANCE;
        partial void OnVARIANCEChanging(global::System.Double value);
        partial void OnVARIANCEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VALUETYPE
        {
            get
            {
                return _VALUETYPE;
            }
            set
            {
                OnVALUETYPEChanging(value);
                ReportPropertyChanging("VALUETYPE");
                _VALUETYPE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VALUETYPE");
                OnVALUETYPEChanged();
            }
        }
        private global::System.Int32 _VALUETYPE;
        partial void OnVALUETYPEChanging(global::System.Int32 value);
        partial void OnVALUETYPEChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JobZoomCoreModel", "FK_Node_NodeDistribution", "DecisionTreeNode")]
        public DecisionTreeNode DecisionTreeNode
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DecisionTreeNode>("JobZoomCoreModel.FK_Node_NodeDistribution", "DecisionTreeNode").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DecisionTreeNode>("JobZoomCoreModel.FK_Node_NodeDistribution", "DecisionTreeNode").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DecisionTreeNode> DecisionTreeNodeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DecisionTreeNode>("JobZoomCoreModel.FK_Node_NodeDistribution", "DecisionTreeNode");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DecisionTreeNode>("JobZoomCoreModel.FK_Node_NodeDistribution", "DecisionTreeNode", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JobZoomCoreModel", Name="SimilarityTerm")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SimilarityTerm : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SimilarityTerm object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="keyword1">Initial value of the Keyword1 property.</param>
        /// <param name="keyword2">Initial value of the Keyword2 property.</param>
        /// <param name="rate">Initial value of the Rate property.</param>
        public static SimilarityTerm CreateSimilarityTerm(global::System.String id, global::System.String keyword1, global::System.String keyword2, global::System.Double rate)
        {
            SimilarityTerm similarityTerm = new SimilarityTerm();
            similarityTerm.ID = id;
            similarityTerm.Keyword1 = keyword1;
            similarityTerm.Keyword2 = keyword2;
            similarityTerm.Rate = rate;
            return similarityTerm;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Keyword1
        {
            get
            {
                return _Keyword1;
            }
            set
            {
                OnKeyword1Changing(value);
                ReportPropertyChanging("Keyword1");
                _Keyword1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Keyword1");
                OnKeyword1Changed();
            }
        }
        private global::System.String _Keyword1;
        partial void OnKeyword1Changing(global::System.String value);
        partial void OnKeyword1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Keyword2
        {
            get
            {
                return _Keyword2;
            }
            set
            {
                OnKeyword2Changing(value);
                ReportPropertyChanging("Keyword2");
                _Keyword2 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Keyword2");
                OnKeyword2Changed();
            }
        }
        private global::System.String _Keyword2;
        partial void OnKeyword2Changing(global::System.String value);
        partial void OnKeyword2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Rate
        {
            get
            {
                return _Rate;
            }
            set
            {
                OnRateChanging(value);
                ReportPropertyChanging("Rate");
                _Rate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rate");
                OnRateChanged();
            }
        }
        private global::System.Double _Rate;
        partial void OnRateChanging(global::System.Double value);
        partial void OnRateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JobZoomCoreModel", Name="TagAttribute")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TagAttribute : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TagAttribute object.
        /// </summary>
        /// <param name="tagId">Initial value of the TagId property.</param>
        /// <param name="tagName">Initial value of the TagName property.</param>
        public static TagAttribute CreateTagAttribute(global::System.Guid tagId, global::System.String tagName)
        {
            TagAttribute tagAttribute = new TagAttribute();
            tagAttribute.TagId = tagId;
            tagAttribute.TagName = tagName;
            return tagAttribute;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TagId
        {
            get
            {
                return _TagId;
            }
            set
            {
                if (_TagId != value)
                {
                    OnTagIdChanging(value);
                    ReportPropertyChanging("TagId");
                    _TagId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TagId");
                    OnTagIdChanged();
                }
            }
        }
        private global::System.Guid _TagId;
        partial void OnTagIdChanging(global::System.Guid value);
        partial void OnTagIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TagName
        {
            get
            {
                return _TagName;
            }
            set
            {
                OnTagNameChanging(value);
                ReportPropertyChanging("TagName");
                _TagName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TagName");
                OnTagNameChanged();
            }
        }
        private global::System.String _TagName;
        partial void OnTagNameChanging(global::System.String value);
        partial void OnTagNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TagValue
        {
            get
            {
                return _TagValue;
            }
            set
            {
                OnTagValueChanging(value);
                ReportPropertyChanging("TagValue");
                _TagValue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TagValue");
                OnTagValueChanged();
            }
        }
        private global::System.String _TagValue;
        partial void OnTagValueChanging(global::System.String value);
        partial void OnTagValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ObjectId
        {
            get
            {
                return _ObjectId;
            }
            set
            {
                OnObjectIdChanging(value);
                ReportPropertyChanging("ObjectId");
                _ObjectId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ObjectId");
                OnObjectIdChanged();
            }
        }
        private Nullable<global::System.Guid> _ObjectId;
        partial void OnObjectIdChanging(Nullable<global::System.Guid> value);
        partial void OnObjectIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ObjectType
        {
            get
            {
                return _ObjectType;
            }
            set
            {
                OnObjectTypeChanging(value);
                ReportPropertyChanging("ObjectType");
                _ObjectType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ObjectType");
                OnObjectTypeChanged();
            }
        }
        private global::System.String _ObjectType;
        partial void OnObjectTypeChanging(global::System.String value);
        partial void OnObjectTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ObjectDeepLevel
        {
            get
            {
                return _ObjectDeepLevel;
            }
            set
            {
                OnObjectDeepLevelChanging(value);
                ReportPropertyChanging("ObjectDeepLevel");
                _ObjectDeepLevel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ObjectDeepLevel");
                OnObjectDeepLevelChanged();
            }
        }
        private Nullable<global::System.Int32> _ObjectDeepLevel;
        partial void OnObjectDeepLevelChanging(Nullable<global::System.Int32> value);
        partial void OnObjectDeepLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private Nullable<global::System.Guid> _ParentId;
        partial void OnParentIdChanging(Nullable<global::System.Guid> value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ParentName
        {
            get
            {
                return _ParentName;
            }
            set
            {
                OnParentNameChanging(value);
                ReportPropertyChanging("ParentName");
                _ParentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ParentName");
                OnParentNameChanged();
            }
        }
        private global::System.String _ParentName;
        partial void OnParentNameChanging(global::System.String value);
        partial void OnParentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                OnWeightChanging(value);
                ReportPropertyChanging("Weight");
                _Weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Weight");
                OnWeightChanged();
            }
        }
        private Nullable<global::System.Int16> _Weight;
        partial void OnWeightChanging(Nullable<global::System.Int16> value);
        partial void OnWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Required
        {
            get
            {
                return _Required;
            }
            set
            {
                OnRequiredChanging(value);
                ReportPropertyChanging("Required");
                _Required = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Required");
                OnRequiredChanged();
            }
        }
        private Nullable<global::System.Boolean> _Required;
        partial void OnRequiredChanging(Nullable<global::System.Boolean> value);
        partial void OnRequiredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ValueType
        {
            get
            {
                return _ValueType;
            }
            set
            {
                OnValueTypeChanging(value);
                ReportPropertyChanging("ValueType");
                _ValueType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ValueType");
                OnValueTypeChanged();
            }
        }
        private global::System.String _ValueType;
        partial void OnValueTypeChanging(global::System.String value);
        partial void OnValueTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TagValueMetric
        {
            get
            {
                return _TagValueMetric;
            }
            set
            {
                OnTagValueMetricChanging(value);
                ReportPropertyChanging("TagValueMetric");
                _TagValueMetric = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TagValueMetric");
                OnTagValueMetricChanged();
            }
        }
        private global::System.String _TagValueMetric;
        partial void OnTagValueMetricChanging(global::System.String value);
        partial void OnTagValueMetricChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Criteria
        {
            get
            {
                return _Criteria;
            }
            set
            {
                OnCriteriaChanging(value);
                ReportPropertyChanging("Criteria");
                _Criteria = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Criteria");
                OnCriteriaChanged();
            }
        }
        private global::System.String _Criteria;
        partial void OnCriteriaChanging(global::System.String value);
        partial void OnCriteriaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TableReference
        {
            get
            {
                return _TableReference;
            }
            set
            {
                OnTableReferenceChanging(value);
                ReportPropertyChanging("TableReference");
                _TableReference = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TableReference");
                OnTableReferenceChanged();
            }
        }
        private global::System.String _TableReference;
        partial void OnTableReferenceChanging(global::System.String value);
        partial void OnTableReferenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Attachment
        {
            get
            {
                return _Attachment;
            }
            set
            {
                OnAttachmentChanging(value);
                ReportPropertyChanging("Attachment");
                _Attachment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Attachment");
                OnAttachmentChanged();
            }
        }
        private global::System.String _Attachment;
        partial void OnAttachmentChanging(global::System.String value);
        partial void OnAttachmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JobZoomCoreModel", "FK_TagAttribute_TagAttribute", "TagAttribute1")]
        public EntityCollection<TagAttribute> TagAttribute1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TagAttribute>("JobZoomCoreModel.FK_TagAttribute_TagAttribute", "TagAttribute1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TagAttribute>("JobZoomCoreModel.FK_TagAttribute_TagAttribute", "TagAttribute1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JobZoomCoreModel", "FK_TagAttribute_TagAttribute", "TagAttribute")]
        public TagAttribute TagAttribute2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TagAttribute>("JobZoomCoreModel.FK_TagAttribute_TagAttribute", "TagAttribute").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TagAttribute>("JobZoomCoreModel.FK_TagAttribute_TagAttribute", "TagAttribute").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TagAttribute> TagAttribute2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TagAttribute>("JobZoomCoreModel.FK_TagAttribute_TagAttribute", "TagAttribute");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TagAttribute>("JobZoomCoreModel.FK_TagAttribute_TagAttribute", "TagAttribute", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
