//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobZoom.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DecisionTreeNode
    {
        public DecisionTreeNode()
        {
            this.DecisionTreeNodeDistributions = new HashSet<DecisionTreeNodeDistribution>();
            this.DecisionTreeNode_Childs = new HashSet<DecisionTreeNode>();
        }
    
        public string NODE_ID { get; set; }
        public string MODEL_NAME { get; set; }
        public int NODE_TYPE { get; set; }
        public string NODE_CAPTION { get; set; }
        public int CHILDREN_CARDINALITY { get; set; }
        public string PARENT_ID { get; set; }
        public string NODE_DESCRIPTION { get; set; }
        public string NODE_RULE { get; set; }
        public string MARGINAL_RULE { get; set; }
        public double NODE_PROBABILITY { get; set; }
        public Nullable<double> MARGINAL_PROBABILITY { get; set; }
        public double NODE_SUPPORT { get; set; }
        public string MSOLAP_MODEL_COLUMN { get; set; }
        public Nullable<double> MSOLAP_NODE_SCORE { get; set; }
        public string MSOLAP_NODE_SHORT_CAPTION { get; set; }
        public string ATTRIBUTE_NAME { get; set; }
    
        public virtual ICollection<DecisionTreeNodeDistribution> DecisionTreeNodeDistributions { get; set; }
        public virtual ICollection<DecisionTreeNode> DecisionTreeNode_Childs { get; set; }
        public virtual DecisionTreeNode DecisionTreeNode_Parent { get; set; }
    }
}
