//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobZoom.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DecisionTreeNodeDistribution
    {
        public string NODE_ID { get; set; }
        public string ATTRIBUTE_NAME { get; set; }
        public string ATTRIBUTE_VALUE { get; set; }
        public double SUPPORT { get; set; }
        public double PROBABILITY { get; set; }
        public double VARIANCE { get; set; }
        public int VALUETYPE { get; set; }
    
        public virtual DecisionTreeNode DecisionTreeNode { get; set; }
    }
}
