//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobZoom.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimilarityTerm
    {
        public string ID { get; set; }
        public string Keyword1 { get; set; }
        public string Keyword2 { get; set; }
        public double Rate { get; set; }
    }
}
