//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobZoom.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagAttribute
    {
        public TagAttribute()
        {
            this.TagAttribute1 = new HashSet<TagAttribute>();
        }
    
        public System.Guid TagId { get; set; }
        public string TagName { get; set; }
        public string TagValue { get; set; }
        public Nullable<System.Guid> ObjectId { get; set; }
        public string ObjectType { get; set; }
        public Nullable<int> ObjectDeepLevel { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string ParentName { get; set; }
        public Nullable<short> Weight { get; set; }
        public Nullable<bool> Required { get; set; }
        public string ValueType { get; set; }
        public string TagValueMetric { get; set; }
        public string Criteria { get; set; }
        public string TableReference { get; set; }
        public string Attachment { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<TagAttribute> TagAttribute1 { get; set; }
        public virtual TagAttribute TagAttribute2 { get; set; }
    }
}
